/**
 * Ashtottari dasha golden: the TS port must reproduce the Python reference. Both
 * run the SAME specs (from ashtottari-golden.json, generated by
 * python/export_ashtottari_golden.py). Strings and structure exact; numbers with
 * tolerance. A closing block checks implementation-independent facts: the eight
 * lord-years total 108, each period's sub-periods tile it, and the JHora/PVR
 * mapping (Punarvasu -> Sun, Rohini -> Venus, Ashwini -> Rahu via the wrap).
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as A from "../src/ashtottari.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/ashtottari-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "lord": return { lord: A.ashtottariLord(spec.nak) };
    case "dashas": return A.ashtottariDashas(spec.moon_lon, jd(spec.natal), 2);
    case "active": return A.ashtottariActive(spec.moon_lon, jd(spec.natal), jd(spec.target));
    case "at": return A.ashtottariAt(eng, jd(spec.natal), jd(spec.target));
    default: throw new Error(`unknown ashtottari type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- invariants, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
{
  const total = A.ASHTOTTARI_ORDER.reduce((a, l) => a + A.ASHTOTTARI_YEARS[l], 0);
  if (total !== 108) fail(`ashtottari years total ${total} != 108`); else ok();

  // JHora/PVR mapping
  if (A.ashtottariLord(6) !== "sun") fail("Punarvasu -> sun"); else ok();
  if (A.ashtottariLord(3) !== "venus") fail("Rohini -> venus"); else ok();
  if (A.ashtottariLord(0) !== "rahu") fail("Ashwini -> rahu (wrap)"); else ok();

  const tl = A.ashtottariDashas(45, jd([1990, 6, 10, 14, 30]), 2);
  for (const m of tl.dashas) {
    if (m.sub.length !== 8) { fail(`${m.lord}: ${m.sub.length} sub-periods`); continue; }
    const tiles = Math.abs(m.sub[0].start - m.start) < 1e-6
      && Math.abs(m.sub[7].end - m.end) < 1e-6
      && m.sub[0].lord === m.lord;
    if (!tiles) fail(`${m.lord}: sub-periods do not tile`); else ok();
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
