/**
 * Derived-charts golden: the TS port of the derivations must reproduce the
 * Python reference's results. Both run the SAME specs (from
 * derived-golden.json, generated by python/export_derived_golden.py) on the
 * same VSOP tier.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as D from "../src/derived.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/derived-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "returns": {
      const n = jd(spec.natal);
      return D.returns(eng, spec.body, n, n + spec.start, n + spec.end);
    }
    case "progressed_jd": return D.progressedJd(jd(spec.natal), jd(spec.target));
    case "solar_arc": return D.solarArc(eng, jd(spec.natal), jd(spec.target));
    case "directed": {
      const n = jd(spec.natal), tg = jd(spec.target);
      const out: Record<string, number> = {};
      for (const b of spec.bodies) out[b] = D.directedLongitude(eng, b, n, tg);
      return out;
    }
    case "composite":
      return D.compositeLongitudes(eng, jd(spec.a), jd(spec.b), spec.bodies);
    case "davison":
      return D.davisonParams(jd(spec.a), jd(spec.b), spec.lat_a, spec.lon_a,
                             spec.lat_b, spec.lon_b);
    default: throw new Error(`unknown derivation type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

function num(id: string, got: number, want: number): void {
  checks++;
  const d = Math.abs(got - want);
  if (d > worst) worst = d;
  if (d > TOL) { failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`); }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function cmp(id: string, got: any, want: any): void {
  if (Array.isArray(want)) {
    checks++;
    if (!Array.isArray(got) || got.length !== want.length) {
      failures++; console.error(`FAIL ${id}: length ${got?.length} vs ${want.length}`); return;
    }
    for (let i = 0; i < want.length; i++) num(`${id}[${i}]`, got[i], want[i]);
  } else if (want !== null && typeof want === "object") {
    for (const k of Object.keys(want)) num(`${id}.${k}`, got[k], want[k]);
  } else {
    num(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) cmp(c.id, compute(c.spec), c.result);

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
