/**
 * Primary directions golden: the TS port must reproduce the Python reference.
 * Both run the SAME specs (from directions-golden.json, generated by
 * python/export_directions_golden.py). Numbers compared with tolerance;
 * structure exact. A closing block checks geometric invariants independent of
 * the golden: IC = MC + 180; a body on the meridian directs to the MC at arc 0;
 * the Ascendant/Descendant arcs relate to MC/IC by the ascensional difference;
 * a circumpolar body has no Asc/Desc direction; and the two keys scale by the
 * Naibod constant.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as D from "../src/directions.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/directions-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "arcs": return D.directionArcs(spec.alpha, spec.delta, spec.ramc, spec.phi);
    case "directions": return D.primaryDirections(eng, jd(spec.natal), spec.lat, spec.lon, undefined, spec.key);
    case "mundane_arc": return { arc: D.mundaneDirectionArc(spec.ap, spec.dp, spec.as_, spec.ds, spec.ramc, spec.phi) };
    case "mundane": return D.mundaneDirections(eng, jd(spec.natal), spec.lat, spec.lon, undefined, spec.key);
    default: throw new Error(`unknown directions type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- geometric invariants, independent of the golden ---
const fail = (msg: string) => { checks++; failures++; console.error(`FAIL ${msg}`); };
const ok = () => { checks++; };
const mod360 = (x: number) => ((x % 360) + 360) % 360;
const RAD = Math.PI / 180, DEG = 180 / Math.PI;
{
  // body exactly on the MC -> arc to MC is 0, to IC is 180
  const onMc = D.directionArcs(50, 0, 50, 40);
  if (Math.abs(onMc.mc) > 1e-9 || Math.abs(onMc.ic - 180) > 1e-9) fail(`on-MC arcs ${JSON.stringify(onMc)}`); else ok();

  // circumpolar body has no oblique ascension
  const cp = D.directionArcs(80, 60, 30, 60);
  if (cp.asc !== null || cp.dsc !== null) fail(`circumpolar asc/dsc not null`); else ok();

  // general relationships across a grid of (alpha, delta, ramc, phi)
  for (const alpha of [10, 100, 250]) for (const delta of [-15, 0, 20]) for (const phi of [-33, 0, 51.5]) {
    const ramc = 75;
    const a = D.directionArcs(alpha, delta, ramc, phi);
    if (Math.abs(mod360(a.mc + 180) - a.ic) > 1e-9) fail(`IC != MC+180 (${alpha},${delta},${phi})`); else ok();
    if (a.asc !== null) {
      const ad = Math.asin(Math.tan(phi * RAD) * Math.tan(delta * RAD)) * DEG;
      if (Math.abs(mod360(a.mc - ad - 90) - a.asc) > 1e-9) fail(`ASC relationship (${alpha},${delta},${phi})`); else ok();
      if (Math.abs(mod360(a.ic + ad - 90) - (a.dsc as number)) > 1e-9) fail(`DSC relationship (${alpha},${delta},${phi})`); else ok();
    }
  }

  // the two keys scale by the Naibod constant
  if (Math.abs(D.directionYears(30, "naibod") - D.directionYears(30, "ptolemy") / 0.9856473) > 1e-9) fail(`key ratio`); else ok();

  // mundane direction invariants, tying it to the validated angle directions:
  // a body directed to itself is 0; an above-horizon promissor directed to a
  // significator on the MC equals its to-MC arc (a below-horizon promissor
  // measures from the IC instead, so the cross-check uses near-meridian, hence
  // above-horizon, promissors).
  if (Math.abs(D.mundaneDirectionArc(100, 20, 100, 20, 50, 40) as number) > 1e-9) fail("mundane self != 0"); else ok();
  for (const [ap, dp, phi] of [[100, 20, 40], [90, -10, 30], [10, 5, -33]] as Array<[number, number, number]>) {
    const ramc = 50;
    const mund = D.mundaneDirectionArc(ap, dp, ramc, 0, ramc, phi) as number; // significator on the MC (alpha = ramc)
    const toMc = D.directionArcs(ap, dp, ramc, phi).mc;
    if (Math.abs(mod360(mund) - toMc) > 1e-6) fail(`mundane-to-MC != to-MC arc (${ap},${dp},${phi}): ${mod360(mund)} vs ${toMc}`); else ok();
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
