/**
 * Draconic golden: the TS port (draconic chart transform) must reproduce the
 * Python reference. Both run the SAME specs (from draconic-golden.json,
 * generated by python/export_draconic_golden.py). Strings and structure
 * exact; numbers with tolerance. A closing block checks the transform's
 * invariants directly, an oracle independent of the golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as DR from "../src/draconic.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/draconic-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "lon": return DR.draconicLongitude(spec.lon, spec.node_lon);
    case "lons": return DR.draconicLongitudes(spec.lons, spec.node_lon);
    case "node_lon": return DR.nodeLongitude(eng, jd(spec.date), spec.node);
    case "chart":
      return DR.draconicChart(eng, jd(spec.date), undefined, spec.node,
                              spec.lat, spec.lon);
    default: throw new Error(`unknown draconic type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- transform invariants, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const near = (a: number, b: number, id: string, tol = 1e-9) => {
  checks++;
  const d = Math.min(Math.abs(a - b), 360 - Math.abs(a - b));
  if (d > tol) { failures++; console.error(`FAIL ${id}: ${a} vs ${b} (diff ${d})`); }
};
{
  const j = julianDay(1987, 11, 2, 23, 10, 0);
  // the anchoring node itself sits at 0 Aries draconic, for both options
  const t = DR.draconicChart(eng, j, ["true_node"], "true");
  const m = DR.draconicChart(eng, j, ["mean_node"], "mean");
  near(t.bodies.true_node, 0, "true-node-at-zero");
  near(m.bodies.mean_node, 0, "mean-node-at-zero");
  // the two node options anchor differently (true vs mean node differ here)
  checks++;
  if (DR.nodeLongitude(eng, j, "true") === DR.nodeLongitude(eng, j, "mean")) {
    fail("true and mean node identical");
  }
  // the transform is a rotation: pairwise separations are preserved
  const c = DR.draconicChart(eng, j, ["sun", "moon"], "true");
  const sun = eng.longitude("sun", j), moon = eng.longitude("moon", j);
  near(((c.bodies.sun - c.bodies.moon) % 360 + 360) % 360,
       ((sun - moon) % 360 + 360) % 360, "rotation-preserves-separations");
  // round trip: adding the node back recovers the tropical longitude
  near(((c.bodies.sun + DR.nodeLongitude(eng, j, "true")) % 360 + 360) % 360,
       sun, "round-trip");
  // pure transform edges: wrap below the node, result always in [0, 360)
  near(DR.draconicLongitude(5, 350), 15, "wrap");
  for (const [lon, node] of [[0, 0], [359.999, 0.001], [0.001, 359.999]]) {
    const d = DR.draconicLongitude(lon, node);
    if (d < 0 || d >= 360) fail(`draconicLongitude(${lon}, ${node}) = ${d} out of range`);
    else checks++;
  }
  // no place given -> no angles key
  checks++;
  if (c.angles !== undefined) fail("angles present without a place");
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
