/**
 * Profections golden: the TS port must reproduce the Python reference. Both run
 * the SAME specs (from profections-golden.json, generated by
 * python/export_profections_golden.py). Numbers compared with tolerance;
 * strings and structure must match exactly. A closing block checks textbook
 * profection facts directly, an oracle independent of either implementation.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as P from "../src/profections.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/profections-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "profection":
      return P.profection(spec.asc_sign, jd(spec.natal), jd(spec.target));
    case "profection_at":
      return P.profectionAt(eng, jd(spec.natal), jd(spec.target), spec.lat, spec.lon,
        spec.zodiac ?? "tropical");
    default: throw new Error(`unknown profections type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// Oracle: textbook profection facts, independent of the golden. Libra (index 6)
// rising — age 0 profects to the 1st house (Libra, lord Venus); age 1 to the
// 2nd (Scorpio, lord Mars); age 12 wraps back to the 1st (Libra).
{
  const a0 = P.profectedSign(6, 0);
  const a1 = P.profectedSign(6, 1);
  const a12 = P.profectedSign(6, 12);
  const want = (got: P.ProfectedSign, sign: string, house: number, lord: string, id: string) => {
    checks++;
    if (got.sign !== sign || got.house !== house || got.lord !== lord) {
      failures++;
      console.error(`FAIL oracle ${id}: ${JSON.stringify(got)} vs {${sign},h${house},${lord}}`);
    }
  };
  want(a0, "Libra", 1, "venus", "libra-age0");
  want(a1, "Scorpio", 2, "mars", "libra-age1");
  want(a12, "Libra", 1, "venus", "libra-age12-wrap");
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
