/**
 * Zodiacal releasing golden: the TS port must reproduce the Python reference.
 * Both run the SAME specs (from releasing-golden.json, generated by
 * python/export_releasing_golden.py). Numbers compared with tolerance; strings
 * and structure exact. A closing block checks implementation-independent
 * invariants sourced from the technique itself: L1 periods tile continuously at
 * period x 360 days; L2 sub-periods tile their L1; the loosing of the bond
 * jumps to the opposite sign (+6); and an L1 contains an L2 loosing of the bond
 * iff its period exceeds the 211-month (~17.58-year) full-loop threshold.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine, SIGNS } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as R from "../src/releasing.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/releasing-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);
const idx = (name: string) => SIGNS.indexOf(name);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "release": return R.zrRelease(spec.lot_sign, jd(spec.natal), spec.max_level, spec.horizon_years);
    case "active": return R.zrActive(spec.lot_sign, jd(spec.natal), jd(spec.target));
    case "at": return R.zrAt(eng, jd(spec.natal), jd(spec.target), spec.lat, spec.lon, spec.lot);
    default: throw new Error(`unknown releasing type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;
let worst = 0;
const TOL = 1e-6;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function leaf(id: string, got: any, want: any): void {
  checks++;
  if (typeof want === "number") {
    const d = Math.abs(got - want);
    if (d > worst) worst = d;
    if (typeof got !== "number" || d > TOL) {
      failures++; console.error(`FAIL ${id}: ${got} vs ${want} (diff ${d})`);
    }
  } else if (got !== want) {
    failures++;
    console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++;
      console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
  } else {
    leaf(id, got, want);
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- invariants, independent of the golden ---
const fail = (msg: string) => { checks++; failures++; console.error(`FAIL ${msg}`); };
const ok = () => { checks++; };
{
  const natal = jd([1990, 6, 10, 14, 30]);
  // Walk a long L1+L2 timeline from each of the twelve possible Lot signs.
  for (let lot = 0; lot < 12; lot++) {
    const tl = R.zrRelease(lot, natal, 2, 220);
    const l1 = tl.filter((p) => p.level === 1);
    // L1 tiles continuously at period x 360 days, first from the Lot sign.
    if (idx(l1[0].sign) !== lot) fail(`lot ${lot}: first L1 is ${l1[0].sign}`);
    else ok();
    for (let i = 0; i < l1.length; i++) {
      const want = R.ZR_PERIODS[idx(l1[i].sign)] * 360;
      const got = l1[i].end - l1[i].start;
      if (Math.abs(got - Math.min(want, natal + 220 * 360 - l1[i].start)) > 1e-6) {
        fail(`lot ${lot}: L1 ${l1[i].sign} length`);
      } else ok();
      if (i > 0 && Math.abs(l1[i].start - l1[i - 1].end) > 1e-6) fail(`lot ${lot}: L1 gap at ${i}`); else ok();
    }
    // For each L1, its L2 children tile it, and an L2 loosing of the bond is
    // present iff the L1 period exceeds the full-loop threshold (>= 18 years).
    for (const p of l1) {
      const subs = tl.filter((s) => s.level === 2 && s.start >= p.start - 1e-9 && s.end <= p.end + 1e-9);
      if (subs.length === 0) continue; // L1 cut by the horizon
      if (Math.abs(subs[0].start - p.start) > 1e-6) fail(`L1 ${p.sign}: L2 start`); else ok();
      if (Math.abs(subs[subs.length - 1].end - p.end) > 1e-6) fail(`L1 ${p.sign}: L2 end`); else ok();
      // every flagged loosing of the bond jumps +6 from the L1 (release) sign
      for (const s of subs) {
        if (s.lb && idx(s.sign) !== (idx(p.sign) + 6) % 12) fail(`L1 ${p.sign}: LB sign ${s.sign} not opposite`);
      }
      // threshold: LB present iff the L1 is long enough to contain a full loop
      const hasLb = subs.some((s) => s.lb);
      const longEnough = R.ZR_PERIODS[idx(p.sign)] * 360 >= 211 * 30; // 6330 days
      // only assert when the L1 is whole (not truncated by the horizon)
      if (Math.abs((p.end - p.start) - R.ZR_PERIODS[idx(p.sign)] * 360) < 1e-6) {
        if (hasLb !== longEnough) fail(`L1 ${p.sign} (${R.ZR_PERIODS[idx(p.sign)]}y): LB=${hasLb}, expected ${longEnough}`);
        else ok();
      }
    }
  }
}

console.log(`\n${checks} checks, ${failures} failures`);
console.log(`worst numeric diff: ${worst.toExponential(2)}`);
process.exit(failures ? 1 : 0);
