/**
 * Yogas golden: the TS port (Vedic placement yogas) must reproduce the Python
 * reference. Both run the SAME specs (from yogas-golden.json, generated by
 * python/export_yogas_golden.py). Structure exact. A closing block re-asserts the
 * defining rule of each yoga on a constructed chart, an oracle independent of the
 * golden.
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { julianDay } from "../src/core.js";
import { Engine } from "../src/chart.js";
import { loadNodeData } from "../src/node-loader.js";
import * as Y from "../src/yogas.js";

const here = dirname(fileURLToPath(import.meta.url));
const G = JSON.parse(readFileSync(join(here, "../../test/yogas-golden.json"), "utf8"));
const data = loadNodeData(join(here, "../../data"), "embedded", "full");
const eng = new Engine(data);

function jd(date: number[]): number {
  return julianDay(date[0], date[1], date[2], date[3] ?? 0, date[4] ?? 0, date[5] ?? 0);
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function compute(spec: any): any {
  switch (spec.type) {
    case "detect": return Y.detectYogas(spec.signs, spec.asc);
    case "at": return Y.yogasAt(eng, jd(spec.natal), spec.lat, spec.lon);
    case "kemadruma": return Y.kemadruma(spec.signs, spec.include_sun ?? false, spec.include_nodes ?? false);
    default: throw new Error(`unknown yogas type ${spec.type}`);
  }
}

let checks = 0;
let failures = 0;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function deepCmp(id: string, got: any, want: any): void {
  if (want !== null && typeof want === "object") {
    if (got === null || typeof got !== "object") {
      checks++; failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs object`);
      return;
    }
    for (const k of Object.keys(want)) deepCmp(`${id}.${k}`, got[k], want[k]);
    for (const k of Object.keys(got)) if (!(k in want)) { checks++; failures++; console.error(`FAIL ${id}.${k}: extra`); }
  } else {
    checks++;
    if (got !== want) { failures++; console.error(`FAIL ${id}: ${JSON.stringify(got)} vs ${JSON.stringify(want)}`); }
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
for (const c of G.cases as any[]) deepCmp(c.id, compute(c.spec), c.result);

// --- oracle: the defining rule of each yoga, independent of the golden ---
const fail = (m: string) => { checks++; failures++; console.error(`FAIL ${m}`); };
const ok = () => { checks++; };
const base = (over: Record<string, number>) => {
  const s: Record<string, number> = { sun: 1, moon: 1, mars: 1, mercury: 1, jupiter: 1, venus: 1, saturn: 1 };
  return { ...s, ...over };
};
const names = (signs: Record<string, number>, asc: number) => Y.detectYogas(signs, asc).map((y) => y.yoga);
{
  // Ruchaka: Mars in own sign (Scorpio, 7) in a kendra (asc Scorpio -> house 1)
  names(base({ mars: 7 }), 7).includes("Ruchaka") ? ok() : fail("Ruchaka not detected");
  // same Mars, but asc Sagittarius -> Mars in 12th, not a kendra
  names(base({ mars: 7 }), 8).includes("Ruchaka") ? fail("Ruchaka detected off-kendra") : ok();
  // Gajakesari: Jupiter 7th from the Moon
  names(base({ moon: 0, jupiter: 6 }), 0).includes("Gajakesari") ? ok() : fail("Gajakesari not detected");
  // Jupiter 5th from the Moon -> not a kendra
  names(base({ moon: 0, jupiter: 4 }), 0).includes("Gajakesari") ? fail("Gajakesari off-kendra") : ok();
  // Budha-Aditya needs Sun and Mercury in one sign
  names(base({ sun: 3, mercury: 3 }), 0).includes("Budha-Aditya") ? ok() : fail("Budha-Aditya not detected");
  names(base({ sun: 3, mercury: 4 }), 0).includes("Budha-Aditya") ? fail("Budha-Aditya across signs") : ok();

  // Kemadruma: an isolated Moon (no graha in 2nd/12th/conjunct) -> present;
  // a graha in the 2nd from the Moon -> absent
  const iso = { sun: 8, moon: 0, mars: 3, mercury: 4, jupiter: 5, venus: 6, saturn: 7 };
  Y.kemadruma(iso).present ? ok() : fail("Kemadruma not detected for an isolated Moon");
  Y.kemadruma({ ...iso, jupiter: 1 }).present ? fail("Kemadruma with a graha in the 2nd") : ok();
  // the Sun is excluded by default; including it changes the result
  const sunCase = { sun: 1, moon: 0, mars: 3, mercury: 4, jupiter: 5, venus: 6, saturn: 7 };
  Y.kemadruma(sunCase).present && !Y.kemadruma(sunCase, true).present ? ok() : fail("Kemadruma include_sun toggle");
}

console.log(`\n${checks} checks, ${failures} failures`);
process.exit(failures ? 1 : 0);
