import { A, H2, P, Code, Nav } from "../../components/Prose";

export const metadata = {
  title: "caelus — validation",
  description: "Two-link verification chain: Swiss Ephemeris validates the reference engine; 1,438 golden checks validate the TypeScript port. CI enforces both.",
};

const BODY_TABLE: Array<[string, string, string, string]> = [
  ["Sun", "0.4″", "0.2″", ""],
  ["Moon (precise tier)", "2.5″", "0.9″", "JPL DE423 fit; residual partly the oracle's own model noise"],
  ["Moon (embedded series)", "9.6″", "2.8″", "60-term ELP abridged"],
  ["Mercury", "0.5″", "0.2″", ""],
  ["Venus", "0.8″", "0.2″", ""],
  ["Mars", "0.7″", "0.2″", ""],
  ["Jupiter", "0.9″", "0.3″", ""],
  ["Saturn", "0.8″", "0.4″", ""],
  ["Uranus", "1.9″", "0.7″", "VSOP87 theory limit"],
  ["Neptune", "4.6″", "2.2″", "VSOP87 theory limit"],
  ["Pluto", "2.5″", "1.0″", "series valid 1885–2099"],
  ["Chiron", "1.0″", "0.3″", "JPL Horizons fit, 1850–2150"],
  ["Mean node", "0.1″", "0.1″", ""],
  ["True node", "61″", "12″", "osculating; < 1′ display precision"],
  ["Ascendant / MC", "3.2″", "—", ""],
  ["Placidus cusps (all 12)", "3.2″", "—", ""],
];

export default function Validation() {
  const td = { padding: "0.15rem 0.8rem 0.15rem 0", verticalAlign: "top" as const };
  return (
    <main>
      <Nav current="/validation" />
      <h1 style={{ letterSpacing: "0.05em" }}>how we know it&rsquo;s right</h1>
      <P>
        An ephemeris you can&rsquo;t verify is an opinion. caelus ships its
        verification as part of the project: a two-link chain in which each
        implementation is held to a measurable standard, enforced by CI on
        every commit.
      </P>
      <H2>link 1 — reference engine vs Swiss Ephemeris</H2>
      <P>
        The Python reference implementation was compared against Swiss
        Ephemeris 2.10 at hundreds of uniformly random instants spanning
        1900–2099: apparent geocentric ecliptic longitude, true equinox of
        date, every body; angles and house cusps across six latitudes
        including polar Iceland. Maximum and RMS disagreement, in arcseconds:
      </P>
      <table style={{ fontSize: "0.85em", lineHeight: 1.55, borderSpacing: 0 }}>
        <thead>
          <tr style={{ opacity: 0.5, textAlign: "left" }}>
            <th style={td}>body</th><th style={td}>max</th><th style={td}>rms</th><th style={td}>note</th>
          </tr>
        </thead>
        <tbody>
          {BODY_TABLE.map(([b, mx, rms, note]) => (
            <tr key={b}>
              <td style={td}>{b}</td><td style={td}>{mx}</td><td style={td}>{rms}</td>
              <td style={{ ...td, opacity: 0.55 }}>{note}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <P dim>
        Scale: chart software displays positions to the arcminute (60″). One
        arcsecond of zodiacal longitude is roughly the Sun&rsquo;s motion in
        25 seconds of clock time — far below the uncertainty of any recorded
        birth time. Every figure above is invisible at display precision.
      </P>
      <H2>link 2 — TypeScript port vs reference engine</H2>
      <P>
        The shipped TypeScript engine is verified against golden fixtures
        generated by the reference implementation: <strong>1,438 checks —
        every body, timescales, nutation, four house systems, speeds,
        retrograde flags, polar-latitude fallback behavior — passing with a
        worst deviation of 1.6 nano-arcseconds.</strong> Both implementations
        run identical algorithms in IEEE doubles, so the tolerance is set a
        million times tighter than astronomical accuracy: a real porting bug
        cannot hide inside it.
      </P>
      <H2>link 3 — independent cross-checks</H2>
      <P>
        Beyond the oracle: the Moon is fit directly to JPL DE423 at 0.19 km
        residual (≈0.1″), so for lunar positions caelus is anchored to the
        same numerical integration the professional ephemerides use. Chiron
        was fit from JPL Horizons and independently agrees with the Swiss
        Ephemeris asteroid integration to 0.85″ worst-case — two unrelated
        pipelines confirming each other. The MCP layer has its own oracle
        suite: aspect-date searches were verified hit-for-hit, to the minute,
        against an independent scan, including retrograde triple-passes.
      </P>
      <H2>run it yourself</H2>
      <P>
        <Code>git clone</Code> the <A href="https://github.com/heavyblotto/caelus">repo</A>,{" "}
        <Code>npm install &amp;&amp; npm run build &amp;&amp; npm test</Code>.
        The conformance suite is the contract: any change that shifts a
        position fails the build. Found a discrepancy against any professional
        ephemeris? That&rsquo;s a bug — please open an issue with the instant
        and coordinates.
      </P>
      <P dim>
        Honest limits: supported date range is 1800–2149 (1850–2150 for the
        precise Moon and Chiron tiers). No eclipses, heliacal events, or
        topocentric positions yet. Placidus is undefined above the polar
        circles — caelus falls back to whole-sign and{" "}
        <em>says so in the response</em> rather than guessing silently.{" "}
        <A href="/notes">How it was built →</A>
      </P>
    </main>
  );
}
