/** Generated by scripts/sync-facts.mjs — do not edit by hand. */
export const GOLDEN_CHECK_CLAIMS = "3,440, 3,440 golden checks, 3,440 fixtures";
export const WORST_NANO_CLAIMS = "0.61 nano-arcsecond";
export const MCP_TOOL_CLAIMS = "35 chart tools, 35 MCP tools, MCP tools (35), thirty-five chart tools, Thirty-five chart tools, thirty-five tools";
export const HOUSE_SYSTEM_CLAIMS = "12 house systems, 12 systems, twelve house systems, Twelve house systems";
export const SIDEREAL_CLAIMS = "7 sidereal, 7 ayanamsas, seven sidereal, seven ayanamsas";
export const DEFAULT_BODY_CLAIMS = "13 bodies, Thirteen in the default";
