// Regenerate the passage registries from data/passages/*.json. Each file is
// one set; the set id is `corpus-<basename>`, the family is read from the
// file's first record (every record in a file shares its family, which
// the validation harness enforces).
//
// One registry module is emitted per batch (src/passages-b1.ts, ...), so a
// bundler can load a batch without pulling the rest of the corpus; the
// subpath exports (src/natal.ts, conditions.ts, degrees.ts, and friends)
// compile one batch each.
// src/passages.ts aggregates them for the package root and the harness.
//
// Run after new slices land:
//   node pipeline/register-sets.mjs && npm run build && npm test
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const DIR = new URL("../data/passages/", import.meta.url).pathname;
const SRC = new URL("../src/", import.meta.url).pathname;

const files = readdirSync(DIR).filter((f) => f.endsWith(".json")).sort();

const varName = (base) =>
  base.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/^b(\d)/, "b$1");

const HEADER = [
  "/**",
  " * GENERATED by pipeline/register-sets.mjs from data/passages/ -- run it",
  " * after new slices land; do not edit the imports or the set list by hand.",
  " */",
];

const byBatch = new Map();
for (const f of files) {
  const m = f.match(/^(b\d+)-/);
  if (!m) {
    console.error(`SKIP ${f}: no batch prefix`);
    continue;
  }
  const list = byBatch.get(m[1]) ?? [];
  list.push(f);
  byBatch.set(m[1], list);
}

const batches = [...byBatch.keys()].sort();
let total = 0;

for (const batch of batches) {
  const lines = [...HEADER];
  const batchFiles = byBatch.get(batch);
  for (const f of batchFiles) {
    const base = f.replace(/\.json$/, "");
    lines.push(`import ${varName(base)} from "../data/passages/${f}" with { type: "json" };`);
  }
  lines.push('import type { Passage, PassageSet } from "./types.js";');
  lines.push("");
  lines.push("const set = (id: string, family: PassageSet[\"family\"], data: unknown): PassageSet => ({");
  lines.push('  id: `corpus-${id}`,');
  lines.push('  version: "0.1.0",');
  lines.push("  family,");
  lines.push("  passages: data as Passage[],");
  lines.push("});");
  lines.push("");
  lines.push("export const passageSets: PassageSet[] = [");
  for (const f of batchFiles) {
    const base = f.replace(/\.json$/, "");
    const records = JSON.parse(readFileSync(DIR + f, "utf8"));
    if (!Array.isArray(records) || records.length === 0) {
      console.error(`SKIP ${f}: not a non-empty array`);
      continue;
    }
    total++;
    const family = records[0].family;
    lines.push(`  set(${JSON.stringify(base)}, ${JSON.stringify(family)}, ${varName(base)}),`);
  }
  lines.push("];");
  lines.push("");
  writeFileSync(`${SRC}passages-${batch}.ts`, lines.join("\n"));
}

const agg = [...HEADER];
for (const batch of batches) {
  agg.push(`import { passageSets as ${batch}Sets } from "./passages-${batch}.js";`);
}
agg.push('import type { Passage, PassageSet } from "./types.js";');
agg.push("");
agg.push("export const passageSets: PassageSet[] = [");
for (const batch of batches) agg.push(`  ...${batch}Sets,`);
agg.push("];");
agg.push("");
agg.push("/** Every written passage across the sets. */");
agg.push("export const passages: Passage[] = passageSets.flatMap((s) => s.passages);");
agg.push("");
writeFileSync(`${SRC}passages.ts`, agg.join("\n"));

console.log(`registries regenerated: ${total} sets across ${batches.join(", ")}`);
