// Regenerate src/passages.ts from data/passages/*.json. Each file is one
// set; the set id is `corpus-<basename>`, the family is read from the
// file's first record (every record in a file shares its family, which
// the validation harness enforces). Run after new slices land:
//   node pipeline/register-sets.mjs && npm run build && npm test
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const DIR = new URL("../data/passages/", import.meta.url).pathname;
const OUT = new URL("../src/passages.ts", import.meta.url).pathname;

const files = readdirSync(DIR).filter((f) => f.endsWith(".json")).sort();

const varName = (base) =>
  base.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase()).replace(/^b(\d)/, "b$1");

const lines = [];
lines.push("/**");
lines.push(" * The written corpus, grouped into sets per family slice. GENERATED by");
lines.push(" * pipeline/register-sets.mjs from data/passages/ -- run it after new");
lines.push(" * slices land; do not edit the imports or the set list by hand.");
lines.push(" */");
for (const f of files) {
  const base = f.replace(/\.json$/, "");
  lines.push(`import ${varName(base)} from "../data/passages/${f}" with { type: "json" };`);
}
lines.push('import type { Passage, PassageSet } from "./types.js";');
lines.push("");
lines.push("const set = (id: string, family: PassageSet[\"family\"], data: unknown): PassageSet => ({");
lines.push('  id: `corpus-${id}`,');
lines.push('  version: "0.1.0",');
lines.push("  family,");
lines.push("  passages: data as Passage[],");
lines.push("});");
lines.push("");
lines.push("export const passageSets: PassageSet[] = [");
for (const f of files) {
  const base = f.replace(/\.json$/, "");
  const records = JSON.parse(readFileSync(DIR + f, "utf8"));
  if (!Array.isArray(records) || records.length === 0) {
    console.error(`SKIP ${f}: not a non-empty array`);
    continue;
  }
  const family = records[0].family;
  lines.push(`  set(${JSON.stringify(base)}, ${JSON.stringify(family)}, ${varName(base)}),`);
}
lines.push("];");
lines.push("");
lines.push("/** Every written passage across the sets. */");
lines.push("export const passages: Passage[] = passageSets.flatMap((s) => s.passages);");
lines.push("");

writeFileSync(OUT, lines.join("\n"));
console.log(`passages.ts regenerated: ${files.length} sets`);
