/**
 * GENERATED by pipeline/register-sets.mjs from data/passages/ -- run it
 * after new slices land; do not edit the imports or the set list by hand.
 */
import b2Stations from "../data/passages/b2-stations.json" with { type: "json" };
import b2TransitHousesJupiter from "../data/passages/b2-transit-houses-jupiter.json" with { type: "json" };
import b2TransitHousesMars from "../data/passages/b2-transit-houses-mars.json" with { type: "json" };
import b2TransitHousesMercury from "../data/passages/b2-transit-houses-mercury.json" with { type: "json" };
import b2TransitHousesMoon from "../data/passages/b2-transit-houses-moon.json" with { type: "json" };
import b2TransitHousesNeptune from "../data/passages/b2-transit-houses-neptune.json" with { type: "json" };
import b2TransitHousesPluto from "../data/passages/b2-transit-houses-pluto.json" with { type: "json" };
import b2TransitHousesSaturn from "../data/passages/b2-transit-houses-saturn.json" with { type: "json" };
import b2TransitHousesSun from "../data/passages/b2-transit-houses-sun.json" with { type: "json" };
import b2TransitHousesUranus from "../data/passages/b2-transit-houses-uranus.json" with { type: "json" };
import b2TransitHousesVenus from "../data/passages/b2-transit-houses-venus.json" with { type: "json" };
import b2TransitsJupiter1 from "../data/passages/b2-transits-jupiter-1.json" with { type: "json" };
import b2TransitsJupiter2 from "../data/passages/b2-transits-jupiter-2.json" with { type: "json" };
import b2TransitsJupiter3 from "../data/passages/b2-transits-jupiter-3.json" with { type: "json" };
import b2TransitsJupiter4 from "../data/passages/b2-transits-jupiter-4.json" with { type: "json" };
import b2TransitsMars1 from "../data/passages/b2-transits-mars-1.json" with { type: "json" };
import b2TransitsMars2 from "../data/passages/b2-transits-mars-2.json" with { type: "json" };
import b2TransitsMars3 from "../data/passages/b2-transits-mars-3.json" with { type: "json" };
import b2TransitsMars4 from "../data/passages/b2-transits-mars-4.json" with { type: "json" };
import b2TransitsMercury1 from "../data/passages/b2-transits-mercury-1.json" with { type: "json" };
import b2TransitsMercury2 from "../data/passages/b2-transits-mercury-2.json" with { type: "json" };
import b2TransitsMercury3 from "../data/passages/b2-transits-mercury-3.json" with { type: "json" };
import b2TransitsMercury4 from "../data/passages/b2-transits-mercury-4.json" with { type: "json" };
import b2TransitsMoon1 from "../data/passages/b2-transits-moon-1.json" with { type: "json" };
import b2TransitsMoon2 from "../data/passages/b2-transits-moon-2.json" with { type: "json" };
import b2TransitsMoon3 from "../data/passages/b2-transits-moon-3.json" with { type: "json" };
import b2TransitsMoon4 from "../data/passages/b2-transits-moon-4.json" with { type: "json" };
import b2TransitsNeptune1 from "../data/passages/b2-transits-neptune-1.json" with { type: "json" };
import b2TransitsNeptune2 from "../data/passages/b2-transits-neptune-2.json" with { type: "json" };
import b2TransitsNeptune3 from "../data/passages/b2-transits-neptune-3.json" with { type: "json" };
import b2TransitsNeptune4 from "../data/passages/b2-transits-neptune-4.json" with { type: "json" };
import b2TransitsNodeMarsJupiter from "../data/passages/b2-transits-node-mars-jupiter.json" with { type: "json" };
import b2TransitsNodeMercuryVenus from "../data/passages/b2-transits-node-mercury-venus.json" with { type: "json" };
import b2TransitsNodeNeptunePluto from "../data/passages/b2-transits-node-neptune-pluto.json" with { type: "json" };
import b2TransitsNodeSaturnUranus from "../data/passages/b2-transits-node-saturn-uranus.json" with { type: "json" };
import b2TransitsNodeSunMoon from "../data/passages/b2-transits-node-sun-moon.json" with { type: "json" };
import b2TransitsPluto1 from "../data/passages/b2-transits-pluto-1.json" with { type: "json" };
import b2TransitsPluto2 from "../data/passages/b2-transits-pluto-2.json" with { type: "json" };
import b2TransitsPluto3 from "../data/passages/b2-transits-pluto-3.json" with { type: "json" };
import b2TransitsPluto4 from "../data/passages/b2-transits-pluto-4.json" with { type: "json" };
import b2TransitsSaturn1 from "../data/passages/b2-transits-saturn-1.json" with { type: "json" };
import b2TransitsSaturn2 from "../data/passages/b2-transits-saturn-2.json" with { type: "json" };
import b2TransitsSaturn3 from "../data/passages/b2-transits-saturn-3.json" with { type: "json" };
import b2TransitsSaturn4 from "../data/passages/b2-transits-saturn-4.json" with { type: "json" };
import b2TransitsSun1 from "../data/passages/b2-transits-sun-1.json" with { type: "json" };
import b2TransitsSun2 from "../data/passages/b2-transits-sun-2.json" with { type: "json" };
import b2TransitsSun3 from "../data/passages/b2-transits-sun-3.json" with { type: "json" };
import b2TransitsSun4 from "../data/passages/b2-transits-sun-4.json" with { type: "json" };
import b2TransitsUranus1 from "../data/passages/b2-transits-uranus-1.json" with { type: "json" };
import b2TransitsUranus2 from "../data/passages/b2-transits-uranus-2.json" with { type: "json" };
import b2TransitsUranus3 from "../data/passages/b2-transits-uranus-3.json" with { type: "json" };
import b2TransitsUranus4 from "../data/passages/b2-transits-uranus-4.json" with { type: "json" };
import b2TransitsVenus1 from "../data/passages/b2-transits-venus-1.json" with { type: "json" };
import b2TransitsVenus2 from "../data/passages/b2-transits-venus-2.json" with { type: "json" };
import b2TransitsVenus3 from "../data/passages/b2-transits-venus-3.json" with { type: "json" };
import b2TransitsVenus4 from "../data/passages/b2-transits-venus-4.json" with { type: "json" };
import type { Passage, PassageSet } from "./types.js";

const set = (id: string, family: PassageSet["family"], data: unknown): PassageSet => ({
  id: `corpus-${id}`,
  version: "0.1.0",
  family,
  passages: data as Passage[],
});

export const passageSets: PassageSet[] = [
  set("b2-stations", "transit-station", b2Stations),
  set("b2-transit-houses-jupiter", "transit-house", b2TransitHousesJupiter),
  set("b2-transit-houses-mars", "transit-house", b2TransitHousesMars),
  set("b2-transit-houses-mercury", "transit-house", b2TransitHousesMercury),
  set("b2-transit-houses-moon", "transit-house", b2TransitHousesMoon),
  set("b2-transit-houses-neptune", "transit-house", b2TransitHousesNeptune),
  set("b2-transit-houses-pluto", "transit-house", b2TransitHousesPluto),
  set("b2-transit-houses-saturn", "transit-house", b2TransitHousesSaturn),
  set("b2-transit-houses-sun", "transit-house", b2TransitHousesSun),
  set("b2-transit-houses-uranus", "transit-house", b2TransitHousesUranus),
  set("b2-transit-houses-venus", "transit-house", b2TransitHousesVenus),
  set("b2-transits-jupiter-1", "transit-aspect", b2TransitsJupiter1),
  set("b2-transits-jupiter-2", "transit-aspect", b2TransitsJupiter2),
  set("b2-transits-jupiter-3", "transit-aspect", b2TransitsJupiter3),
  set("b2-transits-jupiter-4", "transit-aspect", b2TransitsJupiter4),
  set("b2-transits-mars-1", "transit-aspect", b2TransitsMars1),
  set("b2-transits-mars-2", "transit-aspect", b2TransitsMars2),
  set("b2-transits-mars-3", "transit-aspect", b2TransitsMars3),
  set("b2-transits-mars-4", "transit-aspect", b2TransitsMars4),
  set("b2-transits-mercury-1", "transit-aspect", b2TransitsMercury1),
  set("b2-transits-mercury-2", "transit-aspect", b2TransitsMercury2),
  set("b2-transits-mercury-3", "transit-aspect", b2TransitsMercury3),
  set("b2-transits-mercury-4", "transit-aspect", b2TransitsMercury4),
  set("b2-transits-moon-1", "transit-aspect", b2TransitsMoon1),
  set("b2-transits-moon-2", "transit-aspect", b2TransitsMoon2),
  set("b2-transits-moon-3", "transit-aspect", b2TransitsMoon3),
  set("b2-transits-moon-4", "transit-aspect", b2TransitsMoon4),
  set("b2-transits-neptune-1", "transit-aspect", b2TransitsNeptune1),
  set("b2-transits-neptune-2", "transit-aspect", b2TransitsNeptune2),
  set("b2-transits-neptune-3", "transit-aspect", b2TransitsNeptune3),
  set("b2-transits-neptune-4", "transit-aspect", b2TransitsNeptune4),
  set("b2-transits-node-mars-jupiter", "transit-aspect", b2TransitsNodeMarsJupiter),
  set("b2-transits-node-mercury-venus", "transit-aspect", b2TransitsNodeMercuryVenus),
  set("b2-transits-node-neptune-pluto", "transit-aspect", b2TransitsNodeNeptunePluto),
  set("b2-transits-node-saturn-uranus", "transit-aspect", b2TransitsNodeSaturnUranus),
  set("b2-transits-node-sun-moon", "transit-aspect", b2TransitsNodeSunMoon),
  set("b2-transits-pluto-1", "transit-aspect", b2TransitsPluto1),
  set("b2-transits-pluto-2", "transit-aspect", b2TransitsPluto2),
  set("b2-transits-pluto-3", "transit-aspect", b2TransitsPluto3),
  set("b2-transits-pluto-4", "transit-aspect", b2TransitsPluto4),
  set("b2-transits-saturn-1", "transit-aspect", b2TransitsSaturn1),
  set("b2-transits-saturn-2", "transit-aspect", b2TransitsSaturn2),
  set("b2-transits-saturn-3", "transit-aspect", b2TransitsSaturn3),
  set("b2-transits-saturn-4", "transit-aspect", b2TransitsSaturn4),
  set("b2-transits-sun-1", "transit-aspect", b2TransitsSun1),
  set("b2-transits-sun-2", "transit-aspect", b2TransitsSun2),
  set("b2-transits-sun-3", "transit-aspect", b2TransitsSun3),
  set("b2-transits-sun-4", "transit-aspect", b2TransitsSun4),
  set("b2-transits-uranus-1", "transit-aspect", b2TransitsUranus1),
  set("b2-transits-uranus-2", "transit-aspect", b2TransitsUranus2),
  set("b2-transits-uranus-3", "transit-aspect", b2TransitsUranus3),
  set("b2-transits-uranus-4", "transit-aspect", b2TransitsUranus4),
  set("b2-transits-venus-1", "transit-aspect", b2TransitsVenus1),
  set("b2-transits-venus-2", "transit-aspect", b2TransitsVenus2),
  set("b2-transits-venus-3", "transit-aspect", b2TransitsVenus3),
  set("b2-transits-venus-4", "transit-aspect", b2TransitsVenus4),
];
