/**
 * The written corpus, grouped into sets per family slice. GENERATED by
 * pipeline/register-sets.mjs from data/passages/ -- run it after new
 * slices land; do not edit the imports or the set list by hand.
 */
import b1Aspects01 from "../data/passages/b1-aspects-01.json" with { type: "json" };
import b1Aspects02 from "../data/passages/b1-aspects-02.json" with { type: "json" };
import b1Aspects03 from "../data/passages/b1-aspects-03.json" with { type: "json" };
import b1Aspects04 from "../data/passages/b1-aspects-04.json" with { type: "json" };
import b1Aspects05 from "../data/passages/b1-aspects-05.json" with { type: "json" };
import b1Aspects06 from "../data/passages/b1-aspects-06.json" with { type: "json" };
import b1Aspects07 from "../data/passages/b1-aspects-07.json" with { type: "json" };
import b1Aspects08 from "../data/passages/b1-aspects-08.json" with { type: "json" };
import b1Aspects09 from "../data/passages/b1-aspects-09.json" with { type: "json" };
import b1Aspects10 from "../data/passages/b1-aspects-10.json" with { type: "json" };
import b1Aspects11 from "../data/passages/b1-aspects-11.json" with { type: "json" };
import b1Aspects12 from "../data/passages/b1-aspects-12.json" with { type: "json" };
import b1Aspects13 from "../data/passages/b1-aspects-13.json" with { type: "json" };
import b1Aspects14 from "../data/passages/b1-aspects-14.json" with { type: "json" };
import b1Aspects15 from "../data/passages/b1-aspects-15.json" with { type: "json" };
import b1Aspects16 from "../data/passages/b1-aspects-16.json" with { type: "json" };
import b1Aspects17 from "../data/passages/b1-aspects-17.json" with { type: "json" };
import b1Aspects18 from "../data/passages/b1-aspects-18.json" with { type: "json" };
import b1Aspects19 from "../data/passages/b1-aspects-19.json" with { type: "json" };
import b1Aspects20 from "../data/passages/b1-aspects-20.json" with { type: "json" };
import b1Aspects21 from "../data/passages/b1-aspects-21.json" with { type: "json" };
import b1Aspects22 from "../data/passages/b1-aspects-22.json" with { type: "json" };
import b1ChironHouses from "../data/passages/b1-chiron-houses.json" with { type: "json" };
import b1ChironSigns from "../data/passages/b1-chiron-signs.json" with { type: "json" };
import b1Dignities01 from "../data/passages/b1-dignities-01.json" with { type: "json" };
import b1Dignities02 from "../data/passages/b1-dignities-02.json" with { type: "json" };
import b1Dignities03 from "../data/passages/b1-dignities-03.json" with { type: "json" };
import b1Dignities04 from "../data/passages/b1-dignities-04.json" with { type: "json" };
import b1JupiterHouses from "../data/passages/b1-jupiter-houses.json" with { type: "json" };
import b1JupiterSigns from "../data/passages/b1-jupiter-signs.json" with { type: "json" };
import b1MarsHouses from "../data/passages/b1-mars-houses.json" with { type: "json" };
import b1MarsSigns from "../data/passages/b1-mars-signs.json" with { type: "json" };
import b1McSigns from "../data/passages/b1-mc-signs.json" with { type: "json" };
import b1MercuryHouses from "../data/passages/b1-mercury-houses.json" with { type: "json" };
import b1MercurySigns from "../data/passages/b1-mercury-signs.json" with { type: "json" };
import b1MoonHouses from "../data/passages/b1-moon-houses.json" with { type: "json" };
import b1MoonSigns from "../data/passages/b1-moon-signs.json" with { type: "json" };
import b1NatalRetrogrades from "../data/passages/b1-natal-retrogrades.json" with { type: "json" };
import b1NeptuneHouses from "../data/passages/b1-neptune-houses.json" with { type: "json" };
import b1NeptuneSigns from "../data/passages/b1-neptune-signs.json" with { type: "json" };
import b1OnAsc from "../data/passages/b1-on-asc.json" with { type: "json" };
import b1OnDsc from "../data/passages/b1-on-dsc.json" with { type: "json" };
import b1OnIc from "../data/passages/b1-on-ic.json" with { type: "json" };
import b1OnMc from "../data/passages/b1-on-mc.json" with { type: "json" };
import b1OutOfBounds from "../data/passages/b1-out-of-bounds.json" with { type: "json" };
import b1Patterns01 from "../data/passages/b1-patterns-01.json" with { type: "json" };
import b1Patterns02 from "../data/passages/b1-patterns-02.json" with { type: "json" };
import b1PlutoHouses from "../data/passages/b1-pluto-houses.json" with { type: "json" };
import b1PlutoSigns from "../data/passages/b1-pluto-signs.json" with { type: "json" };
import b1RisingSigns from "../data/passages/b1-rising-signs.json" with { type: "json" };
import b1SaturnHouses from "../data/passages/b1-saturn-houses.json" with { type: "json" };
import b1SaturnSigns from "../data/passages/b1-saturn-signs.json" with { type: "json" };
import b1Signature01 from "../data/passages/b1-signature-01.json" with { type: "json" };
import b1Signature02 from "../data/passages/b1-signature-02.json" with { type: "json" };
import b1SunHouses from "../data/passages/b1-sun-houses.json" with { type: "json" };
import b1SunSigns from "../data/passages/b1-sun-signs.json" with { type: "json" };
import b1TrueNodeHouses from "../data/passages/b1-true-node-houses.json" with { type: "json" };
import b1TrueNodeSigns from "../data/passages/b1-true-node-signs.json" with { type: "json" };
import b1UranusHouses from "../data/passages/b1-uranus-houses.json" with { type: "json" };
import b1UranusSigns from "../data/passages/b1-uranus-signs.json" with { type: "json" };
import b1VenusHouses from "../data/passages/b1-venus-houses.json" with { type: "json" };
import b1VenusSigns from "../data/passages/b1-venus-signs.json" with { type: "json" };
import b2Stations from "../data/passages/b2-stations.json" with { type: "json" };
import b2TransitHousesJupiter from "../data/passages/b2-transit-houses-jupiter.json" with { type: "json" };
import b2TransitHousesMars from "../data/passages/b2-transit-houses-mars.json" with { type: "json" };
import b2TransitHousesMercury from "../data/passages/b2-transit-houses-mercury.json" with { type: "json" };
import b2TransitHousesMoon from "../data/passages/b2-transit-houses-moon.json" with { type: "json" };
import b2TransitHousesNeptune from "../data/passages/b2-transit-houses-neptune.json" with { type: "json" };
import b2TransitHousesPluto from "../data/passages/b2-transit-houses-pluto.json" with { type: "json" };
import b2TransitHousesSaturn from "../data/passages/b2-transit-houses-saturn.json" with { type: "json" };
import b2TransitHousesSun from "../data/passages/b2-transit-houses-sun.json" with { type: "json" };
import b2TransitHousesUranus from "../data/passages/b2-transit-houses-uranus.json" with { type: "json" };
import b2TransitHousesVenus from "../data/passages/b2-transit-houses-venus.json" with { type: "json" };
import b2TransitsJupiter1 from "../data/passages/b2-transits-jupiter-1.json" with { type: "json" };
import b2TransitsJupiter2 from "../data/passages/b2-transits-jupiter-2.json" with { type: "json" };
import b2TransitsJupiter3 from "../data/passages/b2-transits-jupiter-3.json" with { type: "json" };
import b2TransitsJupiter4 from "../data/passages/b2-transits-jupiter-4.json" with { type: "json" };
import b2TransitsMars1 from "../data/passages/b2-transits-mars-1.json" with { type: "json" };
import b2TransitsMars2 from "../data/passages/b2-transits-mars-2.json" with { type: "json" };
import b2TransitsMars3 from "../data/passages/b2-transits-mars-3.json" with { type: "json" };
import b2TransitsMars4 from "../data/passages/b2-transits-mars-4.json" with { type: "json" };
import b2TransitsMercury1 from "../data/passages/b2-transits-mercury-1.json" with { type: "json" };
import b2TransitsMercury2 from "../data/passages/b2-transits-mercury-2.json" with { type: "json" };
import b2TransitsMercury3 from "../data/passages/b2-transits-mercury-3.json" with { type: "json" };
import b2TransitsMercury4 from "../data/passages/b2-transits-mercury-4.json" with { type: "json" };
import b2TransitsMoon1 from "../data/passages/b2-transits-moon-1.json" with { type: "json" };
import b2TransitsMoon2 from "../data/passages/b2-transits-moon-2.json" with { type: "json" };
import b2TransitsMoon3 from "../data/passages/b2-transits-moon-3.json" with { type: "json" };
import b2TransitsMoon4 from "../data/passages/b2-transits-moon-4.json" with { type: "json" };
import b2TransitsNeptune1 from "../data/passages/b2-transits-neptune-1.json" with { type: "json" };
import b2TransitsNeptune2 from "../data/passages/b2-transits-neptune-2.json" with { type: "json" };
import b2TransitsNeptune3 from "../data/passages/b2-transits-neptune-3.json" with { type: "json" };
import b2TransitsNeptune4 from "../data/passages/b2-transits-neptune-4.json" with { type: "json" };
import b2TransitsNodeMarsJupiter from "../data/passages/b2-transits-node-mars-jupiter.json" with { type: "json" };
import b2TransitsNodeMercuryVenus from "../data/passages/b2-transits-node-mercury-venus.json" with { type: "json" };
import b2TransitsNodeNeptunePluto from "../data/passages/b2-transits-node-neptune-pluto.json" with { type: "json" };
import b2TransitsNodeSaturnUranus from "../data/passages/b2-transits-node-saturn-uranus.json" with { type: "json" };
import b2TransitsNodeSunMoon from "../data/passages/b2-transits-node-sun-moon.json" with { type: "json" };
import b2TransitsPluto1 from "../data/passages/b2-transits-pluto-1.json" with { type: "json" };
import b2TransitsPluto2 from "../data/passages/b2-transits-pluto-2.json" with { type: "json" };
import b2TransitsPluto3 from "../data/passages/b2-transits-pluto-3.json" with { type: "json" };
import b2TransitsPluto4 from "../data/passages/b2-transits-pluto-4.json" with { type: "json" };
import b2TransitsSaturn1 from "../data/passages/b2-transits-saturn-1.json" with { type: "json" };
import b2TransitsSaturn2 from "../data/passages/b2-transits-saturn-2.json" with { type: "json" };
import b2TransitsSaturn3 from "../data/passages/b2-transits-saturn-3.json" with { type: "json" };
import b2TransitsSaturn4 from "../data/passages/b2-transits-saturn-4.json" with { type: "json" };
import b2TransitsSun1 from "../data/passages/b2-transits-sun-1.json" with { type: "json" };
import b2TransitsSun2 from "../data/passages/b2-transits-sun-2.json" with { type: "json" };
import b2TransitsSun3 from "../data/passages/b2-transits-sun-3.json" with { type: "json" };
import b2TransitsSun4 from "../data/passages/b2-transits-sun-4.json" with { type: "json" };
import b2TransitsUranus1 from "../data/passages/b2-transits-uranus-1.json" with { type: "json" };
import b2TransitsUranus2 from "../data/passages/b2-transits-uranus-2.json" with { type: "json" };
import b2TransitsUranus3 from "../data/passages/b2-transits-uranus-3.json" with { type: "json" };
import b2TransitsUranus4 from "../data/passages/b2-transits-uranus-4.json" with { type: "json" };
import b2TransitsVenus1 from "../data/passages/b2-transits-venus-1.json" with { type: "json" };
import b2TransitsVenus2 from "../data/passages/b2-transits-venus-2.json" with { type: "json" };
import b2TransitsVenus3 from "../data/passages/b2-transits-venus-3.json" with { type: "json" };
import b2TransitsVenus4 from "../data/passages/b2-transits-venus-4.json" with { type: "json" };
import b3CompositeAspectsChiron1 from "../data/passages/b3-composite-aspects-chiron-1.json" with { type: "json" };
import b3CompositeAspectsJupiter1 from "../data/passages/b3-composite-aspects-jupiter-1.json" with { type: "json" };
import b3CompositeAspectsJupiter2 from "../data/passages/b3-composite-aspects-jupiter-2.json" with { type: "json" };
import b3CompositeAspectsMars1 from "../data/passages/b3-composite-aspects-mars-1.json" with { type: "json" };
import b3CompositeAspectsMars2 from "../data/passages/b3-composite-aspects-mars-2.json" with { type: "json" };
import b3CompositeAspectsMars3 from "../data/passages/b3-composite-aspects-mars-3.json" with { type: "json" };
import b3CompositeAspectsMercury1 from "../data/passages/b3-composite-aspects-mercury-1.json" with { type: "json" };
import b3CompositeAspectsMercury2 from "../data/passages/b3-composite-aspects-mercury-2.json" with { type: "json" };
import b3CompositeAspectsMercury3 from "../data/passages/b3-composite-aspects-mercury-3.json" with { type: "json" };
import b3CompositeAspectsMoon1 from "../data/passages/b3-composite-aspects-moon-1.json" with { type: "json" };
import b3CompositeAspectsMoon2 from "../data/passages/b3-composite-aspects-moon-2.json" with { type: "json" };
import b3CompositeAspectsMoon3 from "../data/passages/b3-composite-aspects-moon-3.json" with { type: "json" };
import b3CompositeAspectsMoon4 from "../data/passages/b3-composite-aspects-moon-4.json" with { type: "json" };
import b3CompositeAspectsNeptune1 from "../data/passages/b3-composite-aspects-neptune-1.json" with { type: "json" };
import b3CompositeAspectsPluto1 from "../data/passages/b3-composite-aspects-pluto-1.json" with { type: "json" };
import b3CompositeAspectsSaturn1 from "../data/passages/b3-composite-aspects-saturn-1.json" with { type: "json" };
import b3CompositeAspectsSaturn2 from "../data/passages/b3-composite-aspects-saturn-2.json" with { type: "json" };
import b3CompositeAspectsSun1 from "../data/passages/b3-composite-aspects-sun-1.json" with { type: "json" };
import b3CompositeAspectsSun2 from "../data/passages/b3-composite-aspects-sun-2.json" with { type: "json" };
import b3CompositeAspectsSun3 from "../data/passages/b3-composite-aspects-sun-3.json" with { type: "json" };
import b3CompositeAspectsSun4 from "../data/passages/b3-composite-aspects-sun-4.json" with { type: "json" };
import b3CompositeAspectsUranus1 from "../data/passages/b3-composite-aspects-uranus-1.json" with { type: "json" };
import b3CompositeAspectsUranus2 from "../data/passages/b3-composite-aspects-uranus-2.json" with { type: "json" };
import b3CompositeAspectsVenus1 from "../data/passages/b3-composite-aspects-venus-1.json" with { type: "json" };
import b3CompositeAspectsVenus2 from "../data/passages/b3-composite-aspects-venus-2.json" with { type: "json" };
import b3CompositeAspectsVenus3 from "../data/passages/b3-composite-aspects-venus-3.json" with { type: "json" };
import b3CompositeChiron from "../data/passages/b3-composite-chiron.json" with { type: "json" };
import b3CompositeHousesChiron from "../data/passages/b3-composite-houses-chiron.json" with { type: "json" };
import b3CompositeHousesJupiter from "../data/passages/b3-composite-houses-jupiter.json" with { type: "json" };
import b3CompositeHousesMars from "../data/passages/b3-composite-houses-mars.json" with { type: "json" };
import b3CompositeHousesMercury from "../data/passages/b3-composite-houses-mercury.json" with { type: "json" };
import b3CompositeHousesMoon from "../data/passages/b3-composite-houses-moon.json" with { type: "json" };
import b3CompositeHousesNeptune from "../data/passages/b3-composite-houses-neptune.json" with { type: "json" };
import b3CompositeHousesPluto from "../data/passages/b3-composite-houses-pluto.json" with { type: "json" };
import b3CompositeHousesSaturn from "../data/passages/b3-composite-houses-saturn.json" with { type: "json" };
import b3CompositeHousesSun from "../data/passages/b3-composite-houses-sun.json" with { type: "json" };
import b3CompositeHousesTrueNode from "../data/passages/b3-composite-houses-true-node.json" with { type: "json" };
import b3CompositeHousesUranus from "../data/passages/b3-composite-houses-uranus.json" with { type: "json" };
import b3CompositeHousesVenus from "../data/passages/b3-composite-houses-venus.json" with { type: "json" };
import b3CompositeJupiter from "../data/passages/b3-composite-jupiter.json" with { type: "json" };
import b3CompositeMars from "../data/passages/b3-composite-mars.json" with { type: "json" };
import b3CompositeMercury from "../data/passages/b3-composite-mercury.json" with { type: "json" };
import b3CompositeMoon from "../data/passages/b3-composite-moon.json" with { type: "json" };
import b3CompositeNeptune from "../data/passages/b3-composite-neptune.json" with { type: "json" };
import b3CompositePluto from "../data/passages/b3-composite-pluto.json" with { type: "json" };
import b3CompositeSaturn from "../data/passages/b3-composite-saturn.json" with { type: "json" };
import b3CompositeSun from "../data/passages/b3-composite-sun.json" with { type: "json" };
import b3CompositeTrueNode from "../data/passages/b3-composite-true-node.json" with { type: "json" };
import b3CompositeUranus from "../data/passages/b3-composite-uranus.json" with { type: "json" };
import b3CompositeVenus from "../data/passages/b3-composite-venus.json" with { type: "json" };
import b3SynastryJupiter1 from "../data/passages/b3-synastry-jupiter-1.json" with { type: "json" };
import b3SynastryJupiter2 from "../data/passages/b3-synastry-jupiter-2.json" with { type: "json" };
import b3SynastryJupiter3 from "../data/passages/b3-synastry-jupiter-3.json" with { type: "json" };
import b3SynastryJupiter4 from "../data/passages/b3-synastry-jupiter-4.json" with { type: "json" };
import b3SynastryMars1 from "../data/passages/b3-synastry-mars-1.json" with { type: "json" };
import b3SynastryMars2 from "../data/passages/b3-synastry-mars-2.json" with { type: "json" };
import b3SynastryMars3 from "../data/passages/b3-synastry-mars-3.json" with { type: "json" };
import b3SynastryMars4 from "../data/passages/b3-synastry-mars-4.json" with { type: "json" };
import b3SynastryMercury1 from "../data/passages/b3-synastry-mercury-1.json" with { type: "json" };
import b3SynastryMercury2 from "../data/passages/b3-synastry-mercury-2.json" with { type: "json" };
import b3SynastryMercury3 from "../data/passages/b3-synastry-mercury-3.json" with { type: "json" };
import b3SynastryMercury4 from "../data/passages/b3-synastry-mercury-4.json" with { type: "json" };
import b3SynastryMoon1 from "../data/passages/b3-synastry-moon-1.json" with { type: "json" };
import b3SynastryMoon2 from "../data/passages/b3-synastry-moon-2.json" with { type: "json" };
import b3SynastryMoon3 from "../data/passages/b3-synastry-moon-3.json" with { type: "json" };
import b3SynastryMoon4 from "../data/passages/b3-synastry-moon-4.json" with { type: "json" };
import b3SynastryNeptune1 from "../data/passages/b3-synastry-neptune-1.json" with { type: "json" };
import b3SynastryNeptune2 from "../data/passages/b3-synastry-neptune-2.json" with { type: "json" };
import b3SynastryNeptune3 from "../data/passages/b3-synastry-neptune-3.json" with { type: "json" };
import b3SynastryNeptune4 from "../data/passages/b3-synastry-neptune-4.json" with { type: "json" };
import b3SynastryOverlaysJupiter from "../data/passages/b3-synastry-overlays-jupiter.json" with { type: "json" };
import b3SynastryOverlaysMars from "../data/passages/b3-synastry-overlays-mars.json" with { type: "json" };
import b3SynastryOverlaysMercury from "../data/passages/b3-synastry-overlays-mercury.json" with { type: "json" };
import b3SynastryOverlaysMoon from "../data/passages/b3-synastry-overlays-moon.json" with { type: "json" };
import b3SynastryOverlaysNeptune from "../data/passages/b3-synastry-overlays-neptune.json" with { type: "json" };
import b3SynastryOverlaysPluto from "../data/passages/b3-synastry-overlays-pluto.json" with { type: "json" };
import b3SynastryOverlaysSaturn from "../data/passages/b3-synastry-overlays-saturn.json" with { type: "json" };
import b3SynastryOverlaysSun from "../data/passages/b3-synastry-overlays-sun.json" with { type: "json" };
import b3SynastryOverlaysUranus from "../data/passages/b3-synastry-overlays-uranus.json" with { type: "json" };
import b3SynastryOverlaysVenus from "../data/passages/b3-synastry-overlays-venus.json" with { type: "json" };
import b3SynastryPluto1 from "../data/passages/b3-synastry-pluto-1.json" with { type: "json" };
import b3SynastryPluto2 from "../data/passages/b3-synastry-pluto-2.json" with { type: "json" };
import b3SynastryPluto3 from "../data/passages/b3-synastry-pluto-3.json" with { type: "json" };
import b3SynastryPluto4 from "../data/passages/b3-synastry-pluto-4.json" with { type: "json" };
import b3SynastrySaturn1 from "../data/passages/b3-synastry-saturn-1.json" with { type: "json" };
import b3SynastrySaturn2 from "../data/passages/b3-synastry-saturn-2.json" with { type: "json" };
import b3SynastrySaturn3 from "../data/passages/b3-synastry-saturn-3.json" with { type: "json" };
import b3SynastrySaturn4 from "../data/passages/b3-synastry-saturn-4.json" with { type: "json" };
import b3SynastrySun1 from "../data/passages/b3-synastry-sun-1.json" with { type: "json" };
import b3SynastrySun2 from "../data/passages/b3-synastry-sun-2.json" with { type: "json" };
import b3SynastrySun3 from "../data/passages/b3-synastry-sun-3.json" with { type: "json" };
import b3SynastrySun4 from "../data/passages/b3-synastry-sun-4.json" with { type: "json" };
import b3SynastryUranus1 from "../data/passages/b3-synastry-uranus-1.json" with { type: "json" };
import b3SynastryUranus2 from "../data/passages/b3-synastry-uranus-2.json" with { type: "json" };
import b3SynastryUranus3 from "../data/passages/b3-synastry-uranus-3.json" with { type: "json" };
import b3SynastryUranus4 from "../data/passages/b3-synastry-uranus-4.json" with { type: "json" };
import b3SynastryVenus1 from "../data/passages/b3-synastry-venus-1.json" with { type: "json" };
import b3SynastryVenus2 from "../data/passages/b3-synastry-venus-2.json" with { type: "json" };
import b3SynastryVenus3 from "../data/passages/b3-synastry-venus-3.json" with { type: "json" };
import b3SynastryVenus4 from "../data/passages/b3-synastry-venus-4.json" with { type: "json" };
import b4DashaAntarsJupiter from "../data/passages/b4-dasha-antars-jupiter.json" with { type: "json" };
import b4DashaAntarsKetu from "../data/passages/b4-dasha-antars-ketu.json" with { type: "json" };
import b4DashaAntarsMars from "../data/passages/b4-dasha-antars-mars.json" with { type: "json" };
import b4DashaAntarsMercury from "../data/passages/b4-dasha-antars-mercury.json" with { type: "json" };
import b4DashaAntarsMoon from "../data/passages/b4-dasha-antars-moon.json" with { type: "json" };
import b4DashaAntarsRahu from "../data/passages/b4-dasha-antars-rahu.json" with { type: "json" };
import b4DashaAntarsSaturn from "../data/passages/b4-dasha-antars-saturn.json" with { type: "json" };
import b4DashaAntarsSun from "../data/passages/b4-dasha-antars-sun.json" with { type: "json" };
import b4DashaAntarsVenus from "../data/passages/b4-dasha-antars-venus.json" with { type: "json" };
import b4DashaMahas from "../data/passages/b4-dasha-mahas.json" with { type: "json" };
import b4Eclipses from "../data/passages/b4-eclipses.json" with { type: "json" };
import b4FirdariaMajors from "../data/passages/b4-firdaria-majors.json" with { type: "json" };
import b4FirdariaSubsJupiter from "../data/passages/b4-firdaria-subs-jupiter.json" with { type: "json" };
import b4FirdariaSubsMars from "../data/passages/b4-firdaria-subs-mars.json" with { type: "json" };
import b4FirdariaSubsMercury from "../data/passages/b4-firdaria-subs-mercury.json" with { type: "json" };
import b4FirdariaSubsMoon from "../data/passages/b4-firdaria-subs-moon.json" with { type: "json" };
import b4FirdariaSubsSaturn from "../data/passages/b4-firdaria-subs-saturn.json" with { type: "json" };
import b4FirdariaSubsSun from "../data/passages/b4-firdaria-subs-sun.json" with { type: "json" };
import b4FirdariaSubsVenus from "../data/passages/b4-firdaria-subs-venus.json" with { type: "json" };
import b4LunationsFull from "../data/passages/b4-lunations-full.json" with { type: "json" };
import b4LunationsNew from "../data/passages/b4-lunations-new.json" with { type: "json" };
import b4ProfectionMonthHouses from "../data/passages/b4-profection-month-houses.json" with { type: "json" };
import b4ProfectionYearHouses from "../data/passages/b4-profection-year-houses.json" with { type: "json" };
import b4ProfectionYearLords from "../data/passages/b4-profection-year-lords.json" with { type: "json" };
import b4Returns from "../data/passages/b4-returns.json" with { type: "json" };
import b4SolarPhases from "../data/passages/b4-solar-phases.json" with { type: "json" };
import b4ZrL1 from "../data/passages/b4-zr-l1.json" with { type: "json" };
import b4ZrL2 from "../data/passages/b4-zr-l2.json" with { type: "json" };
import b7FinderEvents1 from "../data/passages/b7-finder-events-1.json" with { type: "json" };
import b7FinderEvents2 from "../data/passages/b7-finder-events-2.json" with { type: "json" };
import b7FinderRisingFit from "../data/passages/b7-finder-rising-fit.json" with { type: "json" };
import type { Passage, PassageSet } from "./types.js";

const set = (id: string, family: PassageSet["family"], data: unknown): PassageSet => ({
  id: `corpus-${id}`,
  version: "0.1.0",
  family,
  passages: data as Passage[],
});

export const passageSets: PassageSet[] = [
  set("b1-aspects-01", "aspect", b1Aspects01),
  set("b1-aspects-02", "aspect", b1Aspects02),
  set("b1-aspects-03", "aspect", b1Aspects03),
  set("b1-aspects-04", "aspect", b1Aspects04),
  set("b1-aspects-05", "aspect", b1Aspects05),
  set("b1-aspects-06", "aspect", b1Aspects06),
  set("b1-aspects-07", "aspect", b1Aspects07),
  set("b1-aspects-08", "aspect", b1Aspects08),
  set("b1-aspects-09", "aspect", b1Aspects09),
  set("b1-aspects-10", "aspect", b1Aspects10),
  set("b1-aspects-11", "aspect", b1Aspects11),
  set("b1-aspects-12", "aspect", b1Aspects12),
  set("b1-aspects-13", "aspect", b1Aspects13),
  set("b1-aspects-14", "aspect", b1Aspects14),
  set("b1-aspects-15", "aspect", b1Aspects15),
  set("b1-aspects-16", "aspect", b1Aspects16),
  set("b1-aspects-17", "aspect", b1Aspects17),
  set("b1-aspects-18", "aspect", b1Aspects18),
  set("b1-aspects-19", "aspect", b1Aspects19),
  set("b1-aspects-20", "aspect", b1Aspects20),
  set("b1-aspects-21", "aspect", b1Aspects21),
  set("b1-aspects-22", "aspect", b1Aspects22),
  set("b1-chiron-houses", "planet-in-house", b1ChironHouses),
  set("b1-chiron-signs", "planet-in-sign", b1ChironSigns),
  set("b1-dignities-01", "dignity", b1Dignities01),
  set("b1-dignities-02", "dignity", b1Dignities02),
  set("b1-dignities-03", "dignity", b1Dignities03),
  set("b1-dignities-04", "dignity", b1Dignities04),
  set("b1-jupiter-houses", "planet-in-house", b1JupiterHouses),
  set("b1-jupiter-signs", "planet-in-sign", b1JupiterSigns),
  set("b1-mars-houses", "planet-in-house", b1MarsHouses),
  set("b1-mars-signs", "planet-in-sign", b1MarsSigns),
  set("b1-mc-signs", "mc-sign", b1McSigns),
  set("b1-mercury-houses", "planet-in-house", b1MercuryHouses),
  set("b1-mercury-signs", "planet-in-sign", b1MercurySigns),
  set("b1-moon-houses", "planet-in-house", b1MoonHouses),
  set("b1-moon-signs", "planet-in-sign", b1MoonSigns),
  set("b1-natal-retrogrades", "natal-retrograde", b1NatalRetrogrades),
  set("b1-neptune-houses", "planet-in-house", b1NeptuneHouses),
  set("b1-neptune-signs", "planet-in-sign", b1NeptuneSigns),
  set("b1-on-asc", "angle-conjunction", b1OnAsc),
  set("b1-on-dsc", "angle-conjunction", b1OnDsc),
  set("b1-on-ic", "angle-conjunction", b1OnIc),
  set("b1-on-mc", "angle-conjunction", b1OnMc),
  set("b1-out-of-bounds", "out-of-bounds", b1OutOfBounds),
  set("b1-patterns-01", "pattern", b1Patterns01),
  set("b1-patterns-02", "pattern", b1Patterns02),
  set("b1-pluto-houses", "planet-in-house", b1PlutoHouses),
  set("b1-pluto-signs", "planet-in-sign", b1PlutoSigns),
  set("b1-rising-signs", "rising-sign", b1RisingSigns),
  set("b1-saturn-houses", "planet-in-house", b1SaturnHouses),
  set("b1-saturn-signs", "planet-in-sign", b1SaturnSigns),
  set("b1-signature-01", "signature", b1Signature01),
  set("b1-signature-02", "signature", b1Signature02),
  set("b1-sun-houses", "planet-in-house", b1SunHouses),
  set("b1-sun-signs", "planet-in-sign", b1SunSigns),
  set("b1-true-node-houses", "planet-in-house", b1TrueNodeHouses),
  set("b1-true-node-signs", "planet-in-sign", b1TrueNodeSigns),
  set("b1-uranus-houses", "planet-in-house", b1UranusHouses),
  set("b1-uranus-signs", "planet-in-sign", b1UranusSigns),
  set("b1-venus-houses", "planet-in-house", b1VenusHouses),
  set("b1-venus-signs", "planet-in-sign", b1VenusSigns),
  set("b2-stations", "transit-station", b2Stations),
  set("b2-transit-houses-jupiter", "transit-house", b2TransitHousesJupiter),
  set("b2-transit-houses-mars", "transit-house", b2TransitHousesMars),
  set("b2-transit-houses-mercury", "transit-house", b2TransitHousesMercury),
  set("b2-transit-houses-moon", "transit-house", b2TransitHousesMoon),
  set("b2-transit-houses-neptune", "transit-house", b2TransitHousesNeptune),
  set("b2-transit-houses-pluto", "transit-house", b2TransitHousesPluto),
  set("b2-transit-houses-saturn", "transit-house", b2TransitHousesSaturn),
  set("b2-transit-houses-sun", "transit-house", b2TransitHousesSun),
  set("b2-transit-houses-uranus", "transit-house", b2TransitHousesUranus),
  set("b2-transit-houses-venus", "transit-house", b2TransitHousesVenus),
  set("b2-transits-jupiter-1", "transit-aspect", b2TransitsJupiter1),
  set("b2-transits-jupiter-2", "transit-aspect", b2TransitsJupiter2),
  set("b2-transits-jupiter-3", "transit-aspect", b2TransitsJupiter3),
  set("b2-transits-jupiter-4", "transit-aspect", b2TransitsJupiter4),
  set("b2-transits-mars-1", "transit-aspect", b2TransitsMars1),
  set("b2-transits-mars-2", "transit-aspect", b2TransitsMars2),
  set("b2-transits-mars-3", "transit-aspect", b2TransitsMars3),
  set("b2-transits-mars-4", "transit-aspect", b2TransitsMars4),
  set("b2-transits-mercury-1", "transit-aspect", b2TransitsMercury1),
  set("b2-transits-mercury-2", "transit-aspect", b2TransitsMercury2),
  set("b2-transits-mercury-3", "transit-aspect", b2TransitsMercury3),
  set("b2-transits-mercury-4", "transit-aspect", b2TransitsMercury4),
  set("b2-transits-moon-1", "transit-aspect", b2TransitsMoon1),
  set("b2-transits-moon-2", "transit-aspect", b2TransitsMoon2),
  set("b2-transits-moon-3", "transit-aspect", b2TransitsMoon3),
  set("b2-transits-moon-4", "transit-aspect", b2TransitsMoon4),
  set("b2-transits-neptune-1", "transit-aspect", b2TransitsNeptune1),
  set("b2-transits-neptune-2", "transit-aspect", b2TransitsNeptune2),
  set("b2-transits-neptune-3", "transit-aspect", b2TransitsNeptune3),
  set("b2-transits-neptune-4", "transit-aspect", b2TransitsNeptune4),
  set("b2-transits-node-mars-jupiter", "transit-aspect", b2TransitsNodeMarsJupiter),
  set("b2-transits-node-mercury-venus", "transit-aspect", b2TransitsNodeMercuryVenus),
  set("b2-transits-node-neptune-pluto", "transit-aspect", b2TransitsNodeNeptunePluto),
  set("b2-transits-node-saturn-uranus", "transit-aspect", b2TransitsNodeSaturnUranus),
  set("b2-transits-node-sun-moon", "transit-aspect", b2TransitsNodeSunMoon),
  set("b2-transits-pluto-1", "transit-aspect", b2TransitsPluto1),
  set("b2-transits-pluto-2", "transit-aspect", b2TransitsPluto2),
  set("b2-transits-pluto-3", "transit-aspect", b2TransitsPluto3),
  set("b2-transits-pluto-4", "transit-aspect", b2TransitsPluto4),
  set("b2-transits-saturn-1", "transit-aspect", b2TransitsSaturn1),
  set("b2-transits-saturn-2", "transit-aspect", b2TransitsSaturn2),
  set("b2-transits-saturn-3", "transit-aspect", b2TransitsSaturn3),
  set("b2-transits-saturn-4", "transit-aspect", b2TransitsSaturn4),
  set("b2-transits-sun-1", "transit-aspect", b2TransitsSun1),
  set("b2-transits-sun-2", "transit-aspect", b2TransitsSun2),
  set("b2-transits-sun-3", "transit-aspect", b2TransitsSun3),
  set("b2-transits-sun-4", "transit-aspect", b2TransitsSun4),
  set("b2-transits-uranus-1", "transit-aspect", b2TransitsUranus1),
  set("b2-transits-uranus-2", "transit-aspect", b2TransitsUranus2),
  set("b2-transits-uranus-3", "transit-aspect", b2TransitsUranus3),
  set("b2-transits-uranus-4", "transit-aspect", b2TransitsUranus4),
  set("b2-transits-venus-1", "transit-aspect", b2TransitsVenus1),
  set("b2-transits-venus-2", "transit-aspect", b2TransitsVenus2),
  set("b2-transits-venus-3", "transit-aspect", b2TransitsVenus3),
  set("b2-transits-venus-4", "transit-aspect", b2TransitsVenus4),
  set("b3-composite-aspects-chiron-1", "composite-aspect", b3CompositeAspectsChiron1),
  set("b3-composite-aspects-jupiter-1", "composite-aspect", b3CompositeAspectsJupiter1),
  set("b3-composite-aspects-jupiter-2", "composite-aspect", b3CompositeAspectsJupiter2),
  set("b3-composite-aspects-mars-1", "composite-aspect", b3CompositeAspectsMars1),
  set("b3-composite-aspects-mars-2", "composite-aspect", b3CompositeAspectsMars2),
  set("b3-composite-aspects-mars-3", "composite-aspect", b3CompositeAspectsMars3),
  set("b3-composite-aspects-mercury-1", "composite-aspect", b3CompositeAspectsMercury1),
  set("b3-composite-aspects-mercury-2", "composite-aspect", b3CompositeAspectsMercury2),
  set("b3-composite-aspects-mercury-3", "composite-aspect", b3CompositeAspectsMercury3),
  set("b3-composite-aspects-moon-1", "composite-aspect", b3CompositeAspectsMoon1),
  set("b3-composite-aspects-moon-2", "composite-aspect", b3CompositeAspectsMoon2),
  set("b3-composite-aspects-moon-3", "composite-aspect", b3CompositeAspectsMoon3),
  set("b3-composite-aspects-moon-4", "composite-aspect", b3CompositeAspectsMoon4),
  set("b3-composite-aspects-neptune-1", "composite-aspect", b3CompositeAspectsNeptune1),
  set("b3-composite-aspects-pluto-1", "composite-aspect", b3CompositeAspectsPluto1),
  set("b3-composite-aspects-saturn-1", "composite-aspect", b3CompositeAspectsSaturn1),
  set("b3-composite-aspects-saturn-2", "composite-aspect", b3CompositeAspectsSaturn2),
  set("b3-composite-aspects-sun-1", "composite-aspect", b3CompositeAspectsSun1),
  set("b3-composite-aspects-sun-2", "composite-aspect", b3CompositeAspectsSun2),
  set("b3-composite-aspects-sun-3", "composite-aspect", b3CompositeAspectsSun3),
  set("b3-composite-aspects-sun-4", "composite-aspect", b3CompositeAspectsSun4),
  set("b3-composite-aspects-uranus-1", "composite-aspect", b3CompositeAspectsUranus1),
  set("b3-composite-aspects-uranus-2", "composite-aspect", b3CompositeAspectsUranus2),
  set("b3-composite-aspects-venus-1", "composite-aspect", b3CompositeAspectsVenus1),
  set("b3-composite-aspects-venus-2", "composite-aspect", b3CompositeAspectsVenus2),
  set("b3-composite-aspects-venus-3", "composite-aspect", b3CompositeAspectsVenus3),
  set("b3-composite-chiron", "composite-placement", b3CompositeChiron),
  set("b3-composite-houses-chiron", "composite-house", b3CompositeHousesChiron),
  set("b3-composite-houses-jupiter", "composite-house", b3CompositeHousesJupiter),
  set("b3-composite-houses-mars", "composite-house", b3CompositeHousesMars),
  set("b3-composite-houses-mercury", "composite-house", b3CompositeHousesMercury),
  set("b3-composite-houses-moon", "composite-house", b3CompositeHousesMoon),
  set("b3-composite-houses-neptune", "composite-house", b3CompositeHousesNeptune),
  set("b3-composite-houses-pluto", "composite-house", b3CompositeHousesPluto),
  set("b3-composite-houses-saturn", "composite-house", b3CompositeHousesSaturn),
  set("b3-composite-houses-sun", "composite-house", b3CompositeHousesSun),
  set("b3-composite-houses-true-node", "composite-house", b3CompositeHousesTrueNode),
  set("b3-composite-houses-uranus", "composite-house", b3CompositeHousesUranus),
  set("b3-composite-houses-venus", "composite-house", b3CompositeHousesVenus),
  set("b3-composite-jupiter", "composite-placement", b3CompositeJupiter),
  set("b3-composite-mars", "composite-placement", b3CompositeMars),
  set("b3-composite-mercury", "composite-placement", b3CompositeMercury),
  set("b3-composite-moon", "composite-placement", b3CompositeMoon),
  set("b3-composite-neptune", "composite-placement", b3CompositeNeptune),
  set("b3-composite-pluto", "composite-placement", b3CompositePluto),
  set("b3-composite-saturn", "composite-placement", b3CompositeSaturn),
  set("b3-composite-sun", "composite-placement", b3CompositeSun),
  set("b3-composite-true-node", "composite-placement", b3CompositeTrueNode),
  set("b3-composite-uranus", "composite-placement", b3CompositeUranus),
  set("b3-composite-venus", "composite-placement", b3CompositeVenus),
  set("b3-synastry-jupiter-1", "synastry-aspect", b3SynastryJupiter1),
  set("b3-synastry-jupiter-2", "synastry-aspect", b3SynastryJupiter2),
  set("b3-synastry-jupiter-3", "synastry-aspect", b3SynastryJupiter3),
  set("b3-synastry-jupiter-4", "synastry-aspect", b3SynastryJupiter4),
  set("b3-synastry-mars-1", "synastry-aspect", b3SynastryMars1),
  set("b3-synastry-mars-2", "synastry-aspect", b3SynastryMars2),
  set("b3-synastry-mars-3", "synastry-aspect", b3SynastryMars3),
  set("b3-synastry-mars-4", "synastry-aspect", b3SynastryMars4),
  set("b3-synastry-mercury-1", "synastry-aspect", b3SynastryMercury1),
  set("b3-synastry-mercury-2", "synastry-aspect", b3SynastryMercury2),
  set("b3-synastry-mercury-3", "synastry-aspect", b3SynastryMercury3),
  set("b3-synastry-mercury-4", "synastry-aspect", b3SynastryMercury4),
  set("b3-synastry-moon-1", "synastry-aspect", b3SynastryMoon1),
  set("b3-synastry-moon-2", "synastry-aspect", b3SynastryMoon2),
  set("b3-synastry-moon-3", "synastry-aspect", b3SynastryMoon3),
  set("b3-synastry-moon-4", "synastry-aspect", b3SynastryMoon4),
  set("b3-synastry-neptune-1", "synastry-aspect", b3SynastryNeptune1),
  set("b3-synastry-neptune-2", "synastry-aspect", b3SynastryNeptune2),
  set("b3-synastry-neptune-3", "synastry-aspect", b3SynastryNeptune3),
  set("b3-synastry-neptune-4", "synastry-aspect", b3SynastryNeptune4),
  set("b3-synastry-overlays-jupiter", "synastry-overlay", b3SynastryOverlaysJupiter),
  set("b3-synastry-overlays-mars", "synastry-overlay", b3SynastryOverlaysMars),
  set("b3-synastry-overlays-mercury", "synastry-overlay", b3SynastryOverlaysMercury),
  set("b3-synastry-overlays-moon", "synastry-overlay", b3SynastryOverlaysMoon),
  set("b3-synastry-overlays-neptune", "synastry-overlay", b3SynastryOverlaysNeptune),
  set("b3-synastry-overlays-pluto", "synastry-overlay", b3SynastryOverlaysPluto),
  set("b3-synastry-overlays-saturn", "synastry-overlay", b3SynastryOverlaysSaturn),
  set("b3-synastry-overlays-sun", "synastry-overlay", b3SynastryOverlaysSun),
  set("b3-synastry-overlays-uranus", "synastry-overlay", b3SynastryOverlaysUranus),
  set("b3-synastry-overlays-venus", "synastry-overlay", b3SynastryOverlaysVenus),
  set("b3-synastry-pluto-1", "synastry-aspect", b3SynastryPluto1),
  set("b3-synastry-pluto-2", "synastry-aspect", b3SynastryPluto2),
  set("b3-synastry-pluto-3", "synastry-aspect", b3SynastryPluto3),
  set("b3-synastry-pluto-4", "synastry-aspect", b3SynastryPluto4),
  set("b3-synastry-saturn-1", "synastry-aspect", b3SynastrySaturn1),
  set("b3-synastry-saturn-2", "synastry-aspect", b3SynastrySaturn2),
  set("b3-synastry-saturn-3", "synastry-aspect", b3SynastrySaturn3),
  set("b3-synastry-saturn-4", "synastry-aspect", b3SynastrySaturn4),
  set("b3-synastry-sun-1", "synastry-aspect", b3SynastrySun1),
  set("b3-synastry-sun-2", "synastry-aspect", b3SynastrySun2),
  set("b3-synastry-sun-3", "synastry-aspect", b3SynastrySun3),
  set("b3-synastry-sun-4", "synastry-aspect", b3SynastrySun4),
  set("b3-synastry-uranus-1", "synastry-aspect", b3SynastryUranus1),
  set("b3-synastry-uranus-2", "synastry-aspect", b3SynastryUranus2),
  set("b3-synastry-uranus-3", "synastry-aspect", b3SynastryUranus3),
  set("b3-synastry-uranus-4", "synastry-aspect", b3SynastryUranus4),
  set("b3-synastry-venus-1", "synastry-aspect", b3SynastryVenus1),
  set("b3-synastry-venus-2", "synastry-aspect", b3SynastryVenus2),
  set("b3-synastry-venus-3", "synastry-aspect", b3SynastryVenus3),
  set("b3-synastry-venus-4", "synastry-aspect", b3SynastryVenus4),
  set("b4-dasha-antars-jupiter", "timelord-dasha", b4DashaAntarsJupiter),
  set("b4-dasha-antars-ketu", "timelord-dasha", b4DashaAntarsKetu),
  set("b4-dasha-antars-mars", "timelord-dasha", b4DashaAntarsMars),
  set("b4-dasha-antars-mercury", "timelord-dasha", b4DashaAntarsMercury),
  set("b4-dasha-antars-moon", "timelord-dasha", b4DashaAntarsMoon),
  set("b4-dasha-antars-rahu", "timelord-dasha", b4DashaAntarsRahu),
  set("b4-dasha-antars-saturn", "timelord-dasha", b4DashaAntarsSaturn),
  set("b4-dasha-antars-sun", "timelord-dasha", b4DashaAntarsSun),
  set("b4-dasha-antars-venus", "timelord-dasha", b4DashaAntarsVenus),
  set("b4-dasha-mahas", "timelord-dasha", b4DashaMahas),
  set("b4-eclipses", "eclipse", b4Eclipses),
  set("b4-firdaria-majors", "timelord-firdaria", b4FirdariaMajors),
  set("b4-firdaria-subs-jupiter", "timelord-firdaria", b4FirdariaSubsJupiter),
  set("b4-firdaria-subs-mars", "timelord-firdaria", b4FirdariaSubsMars),
  set("b4-firdaria-subs-mercury", "timelord-firdaria", b4FirdariaSubsMercury),
  set("b4-firdaria-subs-moon", "timelord-firdaria", b4FirdariaSubsMoon),
  set("b4-firdaria-subs-saturn", "timelord-firdaria", b4FirdariaSubsSaturn),
  set("b4-firdaria-subs-sun", "timelord-firdaria", b4FirdariaSubsSun),
  set("b4-firdaria-subs-venus", "timelord-firdaria", b4FirdariaSubsVenus),
  set("b4-lunations-full", "lunation-house", b4LunationsFull),
  set("b4-lunations-new", "lunation-house", b4LunationsNew),
  set("b4-profection-month-houses", "timelord-profection", b4ProfectionMonthHouses),
  set("b4-profection-year-houses", "timelord-profection", b4ProfectionYearHouses),
  set("b4-profection-year-lords", "timelord-profection", b4ProfectionYearLords),
  set("b4-returns", "planetary-return", b4Returns),
  set("b4-solar-phases", "solar-phase", b4SolarPhases),
  set("b4-zr-l1", "timelord-zr", b4ZrL1),
  set("b4-zr-l2", "timelord-zr", b4ZrL2),
  set("b7-finder-events-1", "finder-event-angle", b7FinderEvents1),
  set("b7-finder-events-2", "finder-event-angle", b7FinderEvents2),
  set("b7-finder-rising-fit", "finder-rising-fit", b7FinderRisingFit),
];

/** Every written passage across the sets. */
export const passages: Passage[] = passageSets.flatMap((s) => s.passages);
