/**
 * GENERATED by pipeline/register-sets.mjs from data/passages/ -- run it
 * after new slices land; do not edit the imports or the set list by hand.
 */
import b3CompositeAspectsChiron1 from "../data/passages/b3-composite-aspects-chiron-1.json" with { type: "json" };
import b3CompositeAspectsJupiter1 from "../data/passages/b3-composite-aspects-jupiter-1.json" with { type: "json" };
import b3CompositeAspectsJupiter2 from "../data/passages/b3-composite-aspects-jupiter-2.json" with { type: "json" };
import b3CompositeAspectsMars1 from "../data/passages/b3-composite-aspects-mars-1.json" with { type: "json" };
import b3CompositeAspectsMars2 from "../data/passages/b3-composite-aspects-mars-2.json" with { type: "json" };
import b3CompositeAspectsMars3 from "../data/passages/b3-composite-aspects-mars-3.json" with { type: "json" };
import b3CompositeAspectsMercury1 from "../data/passages/b3-composite-aspects-mercury-1.json" with { type: "json" };
import b3CompositeAspectsMercury2 from "../data/passages/b3-composite-aspects-mercury-2.json" with { type: "json" };
import b3CompositeAspectsMercury3 from "../data/passages/b3-composite-aspects-mercury-3.json" with { type: "json" };
import b3CompositeAspectsMoon1 from "../data/passages/b3-composite-aspects-moon-1.json" with { type: "json" };
import b3CompositeAspectsMoon2 from "../data/passages/b3-composite-aspects-moon-2.json" with { type: "json" };
import b3CompositeAspectsMoon3 from "../data/passages/b3-composite-aspects-moon-3.json" with { type: "json" };
import b3CompositeAspectsMoon4 from "../data/passages/b3-composite-aspects-moon-4.json" with { type: "json" };
import b3CompositeAspectsNeptune1 from "../data/passages/b3-composite-aspects-neptune-1.json" with { type: "json" };
import b3CompositeAspectsPluto1 from "../data/passages/b3-composite-aspects-pluto-1.json" with { type: "json" };
import b3CompositeAspectsSaturn1 from "../data/passages/b3-composite-aspects-saturn-1.json" with { type: "json" };
import b3CompositeAspectsSaturn2 from "../data/passages/b3-composite-aspects-saturn-2.json" with { type: "json" };
import b3CompositeAspectsSun1 from "../data/passages/b3-composite-aspects-sun-1.json" with { type: "json" };
import b3CompositeAspectsSun2 from "../data/passages/b3-composite-aspects-sun-2.json" with { type: "json" };
import b3CompositeAspectsSun3 from "../data/passages/b3-composite-aspects-sun-3.json" with { type: "json" };
import b3CompositeAspectsSun4 from "../data/passages/b3-composite-aspects-sun-4.json" with { type: "json" };
import b3CompositeAspectsUranus1 from "../data/passages/b3-composite-aspects-uranus-1.json" with { type: "json" };
import b3CompositeAspectsUranus2 from "../data/passages/b3-composite-aspects-uranus-2.json" with { type: "json" };
import b3CompositeAspectsVenus1 from "../data/passages/b3-composite-aspects-venus-1.json" with { type: "json" };
import b3CompositeAspectsVenus2 from "../data/passages/b3-composite-aspects-venus-2.json" with { type: "json" };
import b3CompositeAspectsVenus3 from "../data/passages/b3-composite-aspects-venus-3.json" with { type: "json" };
import b3CompositeChiron from "../data/passages/b3-composite-chiron.json" with { type: "json" };
import b3CompositeHousesChiron from "../data/passages/b3-composite-houses-chiron.json" with { type: "json" };
import b3CompositeHousesJupiter from "../data/passages/b3-composite-houses-jupiter.json" with { type: "json" };
import b3CompositeHousesMars from "../data/passages/b3-composite-houses-mars.json" with { type: "json" };
import b3CompositeHousesMercury from "../data/passages/b3-composite-houses-mercury.json" with { type: "json" };
import b3CompositeHousesMoon from "../data/passages/b3-composite-houses-moon.json" with { type: "json" };
import b3CompositeHousesNeptune from "../data/passages/b3-composite-houses-neptune.json" with { type: "json" };
import b3CompositeHousesPluto from "../data/passages/b3-composite-houses-pluto.json" with { type: "json" };
import b3CompositeHousesSaturn from "../data/passages/b3-composite-houses-saturn.json" with { type: "json" };
import b3CompositeHousesSun from "../data/passages/b3-composite-houses-sun.json" with { type: "json" };
import b3CompositeHousesTrueNode from "../data/passages/b3-composite-houses-true-node.json" with { type: "json" };
import b3CompositeHousesUranus from "../data/passages/b3-composite-houses-uranus.json" with { type: "json" };
import b3CompositeHousesVenus from "../data/passages/b3-composite-houses-venus.json" with { type: "json" };
import b3CompositeJupiter from "../data/passages/b3-composite-jupiter.json" with { type: "json" };
import b3CompositeMars from "../data/passages/b3-composite-mars.json" with { type: "json" };
import b3CompositeMercury from "../data/passages/b3-composite-mercury.json" with { type: "json" };
import b3CompositeMoon from "../data/passages/b3-composite-moon.json" with { type: "json" };
import b3CompositeNeptune from "../data/passages/b3-composite-neptune.json" with { type: "json" };
import b3CompositePluto from "../data/passages/b3-composite-pluto.json" with { type: "json" };
import b3CompositeSaturn from "../data/passages/b3-composite-saturn.json" with { type: "json" };
import b3CompositeSun from "../data/passages/b3-composite-sun.json" with { type: "json" };
import b3CompositeTrueNode from "../data/passages/b3-composite-true-node.json" with { type: "json" };
import b3CompositeUranus from "../data/passages/b3-composite-uranus.json" with { type: "json" };
import b3CompositeVenus from "../data/passages/b3-composite-venus.json" with { type: "json" };
import b3SynastryJupiter1 from "../data/passages/b3-synastry-jupiter-1.json" with { type: "json" };
import b3SynastryJupiter2 from "../data/passages/b3-synastry-jupiter-2.json" with { type: "json" };
import b3SynastryJupiter3 from "../data/passages/b3-synastry-jupiter-3.json" with { type: "json" };
import b3SynastryJupiter4 from "../data/passages/b3-synastry-jupiter-4.json" with { type: "json" };
import b3SynastryMars1 from "../data/passages/b3-synastry-mars-1.json" with { type: "json" };
import b3SynastryMars2 from "../data/passages/b3-synastry-mars-2.json" with { type: "json" };
import b3SynastryMars3 from "../data/passages/b3-synastry-mars-3.json" with { type: "json" };
import b3SynastryMars4 from "../data/passages/b3-synastry-mars-4.json" with { type: "json" };
import b3SynastryMercury1 from "../data/passages/b3-synastry-mercury-1.json" with { type: "json" };
import b3SynastryMercury2 from "../data/passages/b3-synastry-mercury-2.json" with { type: "json" };
import b3SynastryMercury3 from "../data/passages/b3-synastry-mercury-3.json" with { type: "json" };
import b3SynastryMercury4 from "../data/passages/b3-synastry-mercury-4.json" with { type: "json" };
import b3SynastryMoon1 from "../data/passages/b3-synastry-moon-1.json" with { type: "json" };
import b3SynastryMoon2 from "../data/passages/b3-synastry-moon-2.json" with { type: "json" };
import b3SynastryMoon3 from "../data/passages/b3-synastry-moon-3.json" with { type: "json" };
import b3SynastryMoon4 from "../data/passages/b3-synastry-moon-4.json" with { type: "json" };
import b3SynastryNeptune1 from "../data/passages/b3-synastry-neptune-1.json" with { type: "json" };
import b3SynastryNeptune2 from "../data/passages/b3-synastry-neptune-2.json" with { type: "json" };
import b3SynastryNeptune3 from "../data/passages/b3-synastry-neptune-3.json" with { type: "json" };
import b3SynastryNeptune4 from "../data/passages/b3-synastry-neptune-4.json" with { type: "json" };
import b3SynastryOverlaysJupiter from "../data/passages/b3-synastry-overlays-jupiter.json" with { type: "json" };
import b3SynastryOverlaysMars from "../data/passages/b3-synastry-overlays-mars.json" with { type: "json" };
import b3SynastryOverlaysMercury from "../data/passages/b3-synastry-overlays-mercury.json" with { type: "json" };
import b3SynastryOverlaysMoon from "../data/passages/b3-synastry-overlays-moon.json" with { type: "json" };
import b3SynastryOverlaysNeptune from "../data/passages/b3-synastry-overlays-neptune.json" with { type: "json" };
import b3SynastryOverlaysPluto from "../data/passages/b3-synastry-overlays-pluto.json" with { type: "json" };
import b3SynastryOverlaysSaturn from "../data/passages/b3-synastry-overlays-saturn.json" with { type: "json" };
import b3SynastryOverlaysSun from "../data/passages/b3-synastry-overlays-sun.json" with { type: "json" };
import b3SynastryOverlaysUranus from "../data/passages/b3-synastry-overlays-uranus.json" with { type: "json" };
import b3SynastryOverlaysVenus from "../data/passages/b3-synastry-overlays-venus.json" with { type: "json" };
import b3SynastryPluto1 from "../data/passages/b3-synastry-pluto-1.json" with { type: "json" };
import b3SynastryPluto2 from "../data/passages/b3-synastry-pluto-2.json" with { type: "json" };
import b3SynastryPluto3 from "../data/passages/b3-synastry-pluto-3.json" with { type: "json" };
import b3SynastryPluto4 from "../data/passages/b3-synastry-pluto-4.json" with { type: "json" };
import b3SynastrySaturn1 from "../data/passages/b3-synastry-saturn-1.json" with { type: "json" };
import b3SynastrySaturn2 from "../data/passages/b3-synastry-saturn-2.json" with { type: "json" };
import b3SynastrySaturn3 from "../data/passages/b3-synastry-saturn-3.json" with { type: "json" };
import b3SynastrySaturn4 from "../data/passages/b3-synastry-saturn-4.json" with { type: "json" };
import b3SynastrySun1 from "../data/passages/b3-synastry-sun-1.json" with { type: "json" };
import b3SynastrySun2 from "../data/passages/b3-synastry-sun-2.json" with { type: "json" };
import b3SynastrySun3 from "../data/passages/b3-synastry-sun-3.json" with { type: "json" };
import b3SynastrySun4 from "../data/passages/b3-synastry-sun-4.json" with { type: "json" };
import b3SynastryUranus1 from "../data/passages/b3-synastry-uranus-1.json" with { type: "json" };
import b3SynastryUranus2 from "../data/passages/b3-synastry-uranus-2.json" with { type: "json" };
import b3SynastryUranus3 from "../data/passages/b3-synastry-uranus-3.json" with { type: "json" };
import b3SynastryUranus4 from "../data/passages/b3-synastry-uranus-4.json" with { type: "json" };
import b3SynastryVenus1 from "../data/passages/b3-synastry-venus-1.json" with { type: "json" };
import b3SynastryVenus2 from "../data/passages/b3-synastry-venus-2.json" with { type: "json" };
import b3SynastryVenus3 from "../data/passages/b3-synastry-venus-3.json" with { type: "json" };
import b3SynastryVenus4 from "../data/passages/b3-synastry-venus-4.json" with { type: "json" };
import type { Passage, PassageSet } from "./types.js";

const set = (id: string, family: PassageSet["family"], data: unknown): PassageSet => ({
  id: `corpus-${id}`,
  version: "0.1.0",
  family,
  passages: data as Passage[],
});

export const passageSets: PassageSet[] = [
  set("b3-composite-aspects-chiron-1", "composite-aspect", b3CompositeAspectsChiron1),
  set("b3-composite-aspects-jupiter-1", "composite-aspect", b3CompositeAspectsJupiter1),
  set("b3-composite-aspects-jupiter-2", "composite-aspect", b3CompositeAspectsJupiter2),
  set("b3-composite-aspects-mars-1", "composite-aspect", b3CompositeAspectsMars1),
  set("b3-composite-aspects-mars-2", "composite-aspect", b3CompositeAspectsMars2),
  set("b3-composite-aspects-mars-3", "composite-aspect", b3CompositeAspectsMars3),
  set("b3-composite-aspects-mercury-1", "composite-aspect", b3CompositeAspectsMercury1),
  set("b3-composite-aspects-mercury-2", "composite-aspect", b3CompositeAspectsMercury2),
  set("b3-composite-aspects-mercury-3", "composite-aspect", b3CompositeAspectsMercury3),
  set("b3-composite-aspects-moon-1", "composite-aspect", b3CompositeAspectsMoon1),
  set("b3-composite-aspects-moon-2", "composite-aspect", b3CompositeAspectsMoon2),
  set("b3-composite-aspects-moon-3", "composite-aspect", b3CompositeAspectsMoon3),
  set("b3-composite-aspects-moon-4", "composite-aspect", b3CompositeAspectsMoon4),
  set("b3-composite-aspects-neptune-1", "composite-aspect", b3CompositeAspectsNeptune1),
  set("b3-composite-aspects-pluto-1", "composite-aspect", b3CompositeAspectsPluto1),
  set("b3-composite-aspects-saturn-1", "composite-aspect", b3CompositeAspectsSaturn1),
  set("b3-composite-aspects-saturn-2", "composite-aspect", b3CompositeAspectsSaturn2),
  set("b3-composite-aspects-sun-1", "composite-aspect", b3CompositeAspectsSun1),
  set("b3-composite-aspects-sun-2", "composite-aspect", b3CompositeAspectsSun2),
  set("b3-composite-aspects-sun-3", "composite-aspect", b3CompositeAspectsSun3),
  set("b3-composite-aspects-sun-4", "composite-aspect", b3CompositeAspectsSun4),
  set("b3-composite-aspects-uranus-1", "composite-aspect", b3CompositeAspectsUranus1),
  set("b3-composite-aspects-uranus-2", "composite-aspect", b3CompositeAspectsUranus2),
  set("b3-composite-aspects-venus-1", "composite-aspect", b3CompositeAspectsVenus1),
  set("b3-composite-aspects-venus-2", "composite-aspect", b3CompositeAspectsVenus2),
  set("b3-composite-aspects-venus-3", "composite-aspect", b3CompositeAspectsVenus3),
  set("b3-composite-chiron", "composite-placement", b3CompositeChiron),
  set("b3-composite-houses-chiron", "composite-house", b3CompositeHousesChiron),
  set("b3-composite-houses-jupiter", "composite-house", b3CompositeHousesJupiter),
  set("b3-composite-houses-mars", "composite-house", b3CompositeHousesMars),
  set("b3-composite-houses-mercury", "composite-house", b3CompositeHousesMercury),
  set("b3-composite-houses-moon", "composite-house", b3CompositeHousesMoon),
  set("b3-composite-houses-neptune", "composite-house", b3CompositeHousesNeptune),
  set("b3-composite-houses-pluto", "composite-house", b3CompositeHousesPluto),
  set("b3-composite-houses-saturn", "composite-house", b3CompositeHousesSaturn),
  set("b3-composite-houses-sun", "composite-house", b3CompositeHousesSun),
  set("b3-composite-houses-true-node", "composite-house", b3CompositeHousesTrueNode),
  set("b3-composite-houses-uranus", "composite-house", b3CompositeHousesUranus),
  set("b3-composite-houses-venus", "composite-house", b3CompositeHousesVenus),
  set("b3-composite-jupiter", "composite-placement", b3CompositeJupiter),
  set("b3-composite-mars", "composite-placement", b3CompositeMars),
  set("b3-composite-mercury", "composite-placement", b3CompositeMercury),
  set("b3-composite-moon", "composite-placement", b3CompositeMoon),
  set("b3-composite-neptune", "composite-placement", b3CompositeNeptune),
  set("b3-composite-pluto", "composite-placement", b3CompositePluto),
  set("b3-composite-saturn", "composite-placement", b3CompositeSaturn),
  set("b3-composite-sun", "composite-placement", b3CompositeSun),
  set("b3-composite-true-node", "composite-placement", b3CompositeTrueNode),
  set("b3-composite-uranus", "composite-placement", b3CompositeUranus),
  set("b3-composite-venus", "composite-placement", b3CompositeVenus),
  set("b3-synastry-jupiter-1", "synastry-aspect", b3SynastryJupiter1),
  set("b3-synastry-jupiter-2", "synastry-aspect", b3SynastryJupiter2),
  set("b3-synastry-jupiter-3", "synastry-aspect", b3SynastryJupiter3),
  set("b3-synastry-jupiter-4", "synastry-aspect", b3SynastryJupiter4),
  set("b3-synastry-mars-1", "synastry-aspect", b3SynastryMars1),
  set("b3-synastry-mars-2", "synastry-aspect", b3SynastryMars2),
  set("b3-synastry-mars-3", "synastry-aspect", b3SynastryMars3),
  set("b3-synastry-mars-4", "synastry-aspect", b3SynastryMars4),
  set("b3-synastry-mercury-1", "synastry-aspect", b3SynastryMercury1),
  set("b3-synastry-mercury-2", "synastry-aspect", b3SynastryMercury2),
  set("b3-synastry-mercury-3", "synastry-aspect", b3SynastryMercury3),
  set("b3-synastry-mercury-4", "synastry-aspect", b3SynastryMercury4),
  set("b3-synastry-moon-1", "synastry-aspect", b3SynastryMoon1),
  set("b3-synastry-moon-2", "synastry-aspect", b3SynastryMoon2),
  set("b3-synastry-moon-3", "synastry-aspect", b3SynastryMoon3),
  set("b3-synastry-moon-4", "synastry-aspect", b3SynastryMoon4),
  set("b3-synastry-neptune-1", "synastry-aspect", b3SynastryNeptune1),
  set("b3-synastry-neptune-2", "synastry-aspect", b3SynastryNeptune2),
  set("b3-synastry-neptune-3", "synastry-aspect", b3SynastryNeptune3),
  set("b3-synastry-neptune-4", "synastry-aspect", b3SynastryNeptune4),
  set("b3-synastry-overlays-jupiter", "synastry-overlay", b3SynastryOverlaysJupiter),
  set("b3-synastry-overlays-mars", "synastry-overlay", b3SynastryOverlaysMars),
  set("b3-synastry-overlays-mercury", "synastry-overlay", b3SynastryOverlaysMercury),
  set("b3-synastry-overlays-moon", "synastry-overlay", b3SynastryOverlaysMoon),
  set("b3-synastry-overlays-neptune", "synastry-overlay", b3SynastryOverlaysNeptune),
  set("b3-synastry-overlays-pluto", "synastry-overlay", b3SynastryOverlaysPluto),
  set("b3-synastry-overlays-saturn", "synastry-overlay", b3SynastryOverlaysSaturn),
  set("b3-synastry-overlays-sun", "synastry-overlay", b3SynastryOverlaysSun),
  set("b3-synastry-overlays-uranus", "synastry-overlay", b3SynastryOverlaysUranus),
  set("b3-synastry-overlays-venus", "synastry-overlay", b3SynastryOverlaysVenus),
  set("b3-synastry-pluto-1", "synastry-aspect", b3SynastryPluto1),
  set("b3-synastry-pluto-2", "synastry-aspect", b3SynastryPluto2),
  set("b3-synastry-pluto-3", "synastry-aspect", b3SynastryPluto3),
  set("b3-synastry-pluto-4", "synastry-aspect", b3SynastryPluto4),
  set("b3-synastry-saturn-1", "synastry-aspect", b3SynastrySaturn1),
  set("b3-synastry-saturn-2", "synastry-aspect", b3SynastrySaturn2),
  set("b3-synastry-saturn-3", "synastry-aspect", b3SynastrySaturn3),
  set("b3-synastry-saturn-4", "synastry-aspect", b3SynastrySaturn4),
  set("b3-synastry-sun-1", "synastry-aspect", b3SynastrySun1),
  set("b3-synastry-sun-2", "synastry-aspect", b3SynastrySun2),
  set("b3-synastry-sun-3", "synastry-aspect", b3SynastrySun3),
  set("b3-synastry-sun-4", "synastry-aspect", b3SynastrySun4),
  set("b3-synastry-uranus-1", "synastry-aspect", b3SynastryUranus1),
  set("b3-synastry-uranus-2", "synastry-aspect", b3SynastryUranus2),
  set("b3-synastry-uranus-3", "synastry-aspect", b3SynastryUranus3),
  set("b3-synastry-uranus-4", "synastry-aspect", b3SynastryUranus4),
  set("b3-synastry-venus-1", "synastry-aspect", b3SynastryVenus1),
  set("b3-synastry-venus-2", "synastry-aspect", b3SynastryVenus2),
  set("b3-synastry-venus-3", "synastry-aspect", b3SynastryVenus3),
  set("b3-synastry-venus-4", "synastry-aspect", b3SynastryVenus4),
];
