/**
 * GENERATED by pipeline/register-sets.mjs from data/passages/ -- run it
 * after new slices land; do not edit the imports or the set list by hand.
 */
import b4DashaAntarsJupiter from "../data/passages/b4-dasha-antars-jupiter.json" with { type: "json" };
import b4DashaAntarsKetu from "../data/passages/b4-dasha-antars-ketu.json" with { type: "json" };
import b4DashaAntarsMars from "../data/passages/b4-dasha-antars-mars.json" with { type: "json" };
import b4DashaAntarsMercury from "../data/passages/b4-dasha-antars-mercury.json" with { type: "json" };
import b4DashaAntarsMoon from "../data/passages/b4-dasha-antars-moon.json" with { type: "json" };
import b4DashaAntarsRahu from "../data/passages/b4-dasha-antars-rahu.json" with { type: "json" };
import b4DashaAntarsSaturn from "../data/passages/b4-dasha-antars-saturn.json" with { type: "json" };
import b4DashaAntarsSun from "../data/passages/b4-dasha-antars-sun.json" with { type: "json" };
import b4DashaAntarsVenus from "../data/passages/b4-dasha-antars-venus.json" with { type: "json" };
import b4DashaMahas from "../data/passages/b4-dasha-mahas.json" with { type: "json" };
import b4Eclipses from "../data/passages/b4-eclipses.json" with { type: "json" };
import b4FirdariaMajors from "../data/passages/b4-firdaria-majors.json" with { type: "json" };
import b4FirdariaSubsJupiter from "../data/passages/b4-firdaria-subs-jupiter.json" with { type: "json" };
import b4FirdariaSubsMars from "../data/passages/b4-firdaria-subs-mars.json" with { type: "json" };
import b4FirdariaSubsMercury from "../data/passages/b4-firdaria-subs-mercury.json" with { type: "json" };
import b4FirdariaSubsMoon from "../data/passages/b4-firdaria-subs-moon.json" with { type: "json" };
import b4FirdariaSubsSaturn from "../data/passages/b4-firdaria-subs-saturn.json" with { type: "json" };
import b4FirdariaSubsSun from "../data/passages/b4-firdaria-subs-sun.json" with { type: "json" };
import b4FirdariaSubsVenus from "../data/passages/b4-firdaria-subs-venus.json" with { type: "json" };
import b4LunationsFull from "../data/passages/b4-lunations-full.json" with { type: "json" };
import b4LunationsNew from "../data/passages/b4-lunations-new.json" with { type: "json" };
import b4ProfectionMonthHouses from "../data/passages/b4-profection-month-houses.json" with { type: "json" };
import b4ProfectionYearHouses from "../data/passages/b4-profection-year-houses.json" with { type: "json" };
import b4ProfectionYearLords from "../data/passages/b4-profection-year-lords.json" with { type: "json" };
import b4Returns from "../data/passages/b4-returns.json" with { type: "json" };
import b4SolarPhases from "../data/passages/b4-solar-phases.json" with { type: "json" };
import b4ZrL1 from "../data/passages/b4-zr-l1.json" with { type: "json" };
import b4ZrL2 from "../data/passages/b4-zr-l2.json" with { type: "json" };
import type { Passage, PassageSet } from "./types.js";

const set = (id: string, family: PassageSet["family"], data: unknown): PassageSet => ({
  id: `corpus-${id}`,
  version: "0.1.0",
  family,
  passages: data as Passage[],
});

export const passageSets: PassageSet[] = [
  set("b4-dasha-antars-jupiter", "timelord-dasha", b4DashaAntarsJupiter),
  set("b4-dasha-antars-ketu", "timelord-dasha", b4DashaAntarsKetu),
  set("b4-dasha-antars-mars", "timelord-dasha", b4DashaAntarsMars),
  set("b4-dasha-antars-mercury", "timelord-dasha", b4DashaAntarsMercury),
  set("b4-dasha-antars-moon", "timelord-dasha", b4DashaAntarsMoon),
  set("b4-dasha-antars-rahu", "timelord-dasha", b4DashaAntarsRahu),
  set("b4-dasha-antars-saturn", "timelord-dasha", b4DashaAntarsSaturn),
  set("b4-dasha-antars-sun", "timelord-dasha", b4DashaAntarsSun),
  set("b4-dasha-antars-venus", "timelord-dasha", b4DashaAntarsVenus),
  set("b4-dasha-mahas", "timelord-dasha", b4DashaMahas),
  set("b4-eclipses", "eclipse", b4Eclipses),
  set("b4-firdaria-majors", "timelord-firdaria", b4FirdariaMajors),
  set("b4-firdaria-subs-jupiter", "timelord-firdaria", b4FirdariaSubsJupiter),
  set("b4-firdaria-subs-mars", "timelord-firdaria", b4FirdariaSubsMars),
  set("b4-firdaria-subs-mercury", "timelord-firdaria", b4FirdariaSubsMercury),
  set("b4-firdaria-subs-moon", "timelord-firdaria", b4FirdariaSubsMoon),
  set("b4-firdaria-subs-saturn", "timelord-firdaria", b4FirdariaSubsSaturn),
  set("b4-firdaria-subs-sun", "timelord-firdaria", b4FirdariaSubsSun),
  set("b4-firdaria-subs-venus", "timelord-firdaria", b4FirdariaSubsVenus),
  set("b4-lunations-full", "lunation-house", b4LunationsFull),
  set("b4-lunations-new", "lunation-house", b4LunationsNew),
  set("b4-profection-month-houses", "timelord-profection", b4ProfectionMonthHouses),
  set("b4-profection-year-houses", "timelord-profection", b4ProfectionYearHouses),
  set("b4-profection-year-lords", "timelord-profection", b4ProfectionYearLords),
  set("b4-returns", "planetary-return", b4Returns),
  set("b4-solar-phases", "solar-phase", b4SolarPhases),
  set("b4-zr-l1", "timelord-zr", b4ZrL1),
  set("b4-zr-l2", "timelord-zr", b4ZrL2),
];
