/**
 * GENERATED by pipeline/register-sets.mjs from data/passages/ -- run it
 * after new slices land; do not edit the imports or the set list by hand.
 */
import b1Aspects01 from "../data/passages/b1-aspects-01.json" with { type: "json" };
import b1Aspects02 from "../data/passages/b1-aspects-02.json" with { type: "json" };
import b1Aspects03 from "../data/passages/b1-aspects-03.json" with { type: "json" };
import b1Aspects04 from "../data/passages/b1-aspects-04.json" with { type: "json" };
import b1Aspects05 from "../data/passages/b1-aspects-05.json" with { type: "json" };
import b1Aspects06 from "../data/passages/b1-aspects-06.json" with { type: "json" };
import b1Aspects07 from "../data/passages/b1-aspects-07.json" with { type: "json" };
import b1Aspects08 from "../data/passages/b1-aspects-08.json" with { type: "json" };
import b1Aspects09 from "../data/passages/b1-aspects-09.json" with { type: "json" };
import b1Aspects10 from "../data/passages/b1-aspects-10.json" with { type: "json" };
import b1Aspects11 from "../data/passages/b1-aspects-11.json" with { type: "json" };
import b1Aspects12 from "../data/passages/b1-aspects-12.json" with { type: "json" };
import b1Aspects13 from "../data/passages/b1-aspects-13.json" with { type: "json" };
import b1Aspects14 from "../data/passages/b1-aspects-14.json" with { type: "json" };
import b1Aspects15 from "../data/passages/b1-aspects-15.json" with { type: "json" };
import b1Aspects16 from "../data/passages/b1-aspects-16.json" with { type: "json" };
import b1Aspects17 from "../data/passages/b1-aspects-17.json" with { type: "json" };
import b1Aspects18 from "../data/passages/b1-aspects-18.json" with { type: "json" };
import b1Aspects19 from "../data/passages/b1-aspects-19.json" with { type: "json" };
import b1Aspects20 from "../data/passages/b1-aspects-20.json" with { type: "json" };
import b1Aspects21 from "../data/passages/b1-aspects-21.json" with { type: "json" };
import b1Aspects22 from "../data/passages/b1-aspects-22.json" with { type: "json" };
import b1ChironHouses from "../data/passages/b1-chiron-houses.json" with { type: "json" };
import b1ChironSigns from "../data/passages/b1-chiron-signs.json" with { type: "json" };
import b1Dignities01 from "../data/passages/b1-dignities-01.json" with { type: "json" };
import b1Dignities02 from "../data/passages/b1-dignities-02.json" with { type: "json" };
import b1Dignities03 from "../data/passages/b1-dignities-03.json" with { type: "json" };
import b1Dignities04 from "../data/passages/b1-dignities-04.json" with { type: "json" };
import b1JupiterHouses from "../data/passages/b1-jupiter-houses.json" with { type: "json" };
import b1JupiterSigns from "../data/passages/b1-jupiter-signs.json" with { type: "json" };
import b1MarsHouses from "../data/passages/b1-mars-houses.json" with { type: "json" };
import b1MarsSigns from "../data/passages/b1-mars-signs.json" with { type: "json" };
import b1McSigns from "../data/passages/b1-mc-signs.json" with { type: "json" };
import b1MercuryHouses from "../data/passages/b1-mercury-houses.json" with { type: "json" };
import b1MercurySigns from "../data/passages/b1-mercury-signs.json" with { type: "json" };
import b1MoonHouses from "../data/passages/b1-moon-houses.json" with { type: "json" };
import b1MoonSigns from "../data/passages/b1-moon-signs.json" with { type: "json" };
import b1NatalRetrogrades from "../data/passages/b1-natal-retrogrades.json" with { type: "json" };
import b1NeptuneHouses from "../data/passages/b1-neptune-houses.json" with { type: "json" };
import b1NeptuneSigns from "../data/passages/b1-neptune-signs.json" with { type: "json" };
import b1OnAsc from "../data/passages/b1-on-asc.json" with { type: "json" };
import b1OnDsc from "../data/passages/b1-on-dsc.json" with { type: "json" };
import b1OnIc from "../data/passages/b1-on-ic.json" with { type: "json" };
import b1OnMc from "../data/passages/b1-on-mc.json" with { type: "json" };
import b1OutOfBounds from "../data/passages/b1-out-of-bounds.json" with { type: "json" };
import b1Patterns01 from "../data/passages/b1-patterns-01.json" with { type: "json" };
import b1Patterns02 from "../data/passages/b1-patterns-02.json" with { type: "json" };
import b1PlutoHouses from "../data/passages/b1-pluto-houses.json" with { type: "json" };
import b1PlutoSigns from "../data/passages/b1-pluto-signs.json" with { type: "json" };
import b1RisingSigns from "../data/passages/b1-rising-signs.json" with { type: "json" };
import b1SaturnHouses from "../data/passages/b1-saturn-houses.json" with { type: "json" };
import b1SaturnSigns from "../data/passages/b1-saturn-signs.json" with { type: "json" };
import b1Signature01 from "../data/passages/b1-signature-01.json" with { type: "json" };
import b1Signature02 from "../data/passages/b1-signature-02.json" with { type: "json" };
import b1SunHouses from "../data/passages/b1-sun-houses.json" with { type: "json" };
import b1SunSigns from "../data/passages/b1-sun-signs.json" with { type: "json" };
import b1TrueNodeHouses from "../data/passages/b1-true-node-houses.json" with { type: "json" };
import b1TrueNodeSigns from "../data/passages/b1-true-node-signs.json" with { type: "json" };
import b1UranusHouses from "../data/passages/b1-uranus-houses.json" with { type: "json" };
import b1UranusSigns from "../data/passages/b1-uranus-signs.json" with { type: "json" };
import b1VenusHouses from "../data/passages/b1-venus-houses.json" with { type: "json" };
import b1VenusSigns from "../data/passages/b1-venus-signs.json" with { type: "json" };
import type { Passage, PassageSet } from "./types.js";

const set = (id: string, family: PassageSet["family"], data: unknown): PassageSet => ({
  id: `corpus-${id}`,
  version: "0.1.0",
  family,
  passages: data as Passage[],
});

export const passageSets: PassageSet[] = [
  set("b1-aspects-01", "aspect", b1Aspects01),
  set("b1-aspects-02", "aspect", b1Aspects02),
  set("b1-aspects-03", "aspect", b1Aspects03),
  set("b1-aspects-04", "aspect", b1Aspects04),
  set("b1-aspects-05", "aspect", b1Aspects05),
  set("b1-aspects-06", "aspect", b1Aspects06),
  set("b1-aspects-07", "aspect", b1Aspects07),
  set("b1-aspects-08", "aspect", b1Aspects08),
  set("b1-aspects-09", "aspect", b1Aspects09),
  set("b1-aspects-10", "aspect", b1Aspects10),
  set("b1-aspects-11", "aspect", b1Aspects11),
  set("b1-aspects-12", "aspect", b1Aspects12),
  set("b1-aspects-13", "aspect", b1Aspects13),
  set("b1-aspects-14", "aspect", b1Aspects14),
  set("b1-aspects-15", "aspect", b1Aspects15),
  set("b1-aspects-16", "aspect", b1Aspects16),
  set("b1-aspects-17", "aspect", b1Aspects17),
  set("b1-aspects-18", "aspect", b1Aspects18),
  set("b1-aspects-19", "aspect", b1Aspects19),
  set("b1-aspects-20", "aspect", b1Aspects20),
  set("b1-aspects-21", "aspect", b1Aspects21),
  set("b1-aspects-22", "aspect", b1Aspects22),
  set("b1-chiron-houses", "planet-in-house", b1ChironHouses),
  set("b1-chiron-signs", "planet-in-sign", b1ChironSigns),
  set("b1-dignities-01", "dignity", b1Dignities01),
  set("b1-dignities-02", "dignity", b1Dignities02),
  set("b1-dignities-03", "dignity", b1Dignities03),
  set("b1-dignities-04", "dignity", b1Dignities04),
  set("b1-jupiter-houses", "planet-in-house", b1JupiterHouses),
  set("b1-jupiter-signs", "planet-in-sign", b1JupiterSigns),
  set("b1-mars-houses", "planet-in-house", b1MarsHouses),
  set("b1-mars-signs", "planet-in-sign", b1MarsSigns),
  set("b1-mc-signs", "mc-sign", b1McSigns),
  set("b1-mercury-houses", "planet-in-house", b1MercuryHouses),
  set("b1-mercury-signs", "planet-in-sign", b1MercurySigns),
  set("b1-moon-houses", "planet-in-house", b1MoonHouses),
  set("b1-moon-signs", "planet-in-sign", b1MoonSigns),
  set("b1-natal-retrogrades", "natal-retrograde", b1NatalRetrogrades),
  set("b1-neptune-houses", "planet-in-house", b1NeptuneHouses),
  set("b1-neptune-signs", "planet-in-sign", b1NeptuneSigns),
  set("b1-on-asc", "angle-conjunction", b1OnAsc),
  set("b1-on-dsc", "angle-conjunction", b1OnDsc),
  set("b1-on-ic", "angle-conjunction", b1OnIc),
  set("b1-on-mc", "angle-conjunction", b1OnMc),
  set("b1-out-of-bounds", "out-of-bounds", b1OutOfBounds),
  set("b1-patterns-01", "pattern", b1Patterns01),
  set("b1-patterns-02", "pattern", b1Patterns02),
  set("b1-pluto-houses", "planet-in-house", b1PlutoHouses),
  set("b1-pluto-signs", "planet-in-sign", b1PlutoSigns),
  set("b1-rising-signs", "rising-sign", b1RisingSigns),
  set("b1-saturn-houses", "planet-in-house", b1SaturnHouses),
  set("b1-saturn-signs", "planet-in-sign", b1SaturnSigns),
  set("b1-signature-01", "signature", b1Signature01),
  set("b1-signature-02", "signature", b1Signature02),
  set("b1-sun-houses", "planet-in-house", b1SunHouses),
  set("b1-sun-signs", "planet-in-sign", b1SunSigns),
  set("b1-true-node-houses", "planet-in-house", b1TrueNodeHouses),
  set("b1-true-node-signs", "planet-in-sign", b1TrueNodeSigns),
  set("b1-uranus-houses", "planet-in-house", b1UranusHouses),
  set("b1-uranus-signs", "planet-in-sign", b1UranusSigns),
  set("b1-venus-houses", "planet-in-house", b1VenusHouses),
  set("b1-venus-signs", "planet-in-sign", b1VenusSigns),
];
