/**
 * GENERATED by pipeline/register-sets.mjs from data/passages/ -- run it
 * after new slices land; do not edit the imports or the set list by hand.
 */
import { passageSets as b1Sets } from "./passages-b1.js";
import { passageSets as b2Sets } from "./passages-b2.js";
import { passageSets as b3Sets } from "./passages-b3.js";
import { passageSets as b4Sets } from "./passages-b4.js";
import type { Passage, PassageSet } from "./types.js";

export const passageSets: PassageSet[] = [
  ...b1Sets,
  ...b2Sets,
  ...b3Sets,
  ...b4Sets,
];

/** Every written passage across the sets. */
export const passages: Passage[] = passageSets.flatMap((s) => s.passages);
